<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CarBrand;

class CarBrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            [
                'name' => 'Toyota',
                'slug' => 'toyota',
                'logo_path' => 'images/logos/toyota.png',
                'country' => 'Japan',
                'description' => 'Thương hiệu xe hơi phổ biến tại Việt Nam với nhiều dòng xe bền bỉ, tiết kiệm.',
                'meta_title' => 'Toyota Việt Nam',
                'meta_description' => 'Các dòng xe Toyota chính hãng mới nhất tại Việt Nam.',
                'keywords' => 'toyota, xe toyota, vios, cross, fortuner',
                'founded_year' => 1937,
                'website' => 'https://www.toyota.com.vn',
                'phone' => '028 1234 5678',
                'email' => 'contact@toyota.com.vn',
                'address' => 'Lô E2, Đường D2, KCN Tân Phú Trung, TP.HCM',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Hyundai',
                'slug' => 'hyundai',
                'logo_path' => 'images/logos/hyundai.png',
                'country' => 'South Korea',
                'description' => 'Hãng xe Hàn Quốc với thiết kế hiện đại, nhiều trang bị.',
                'meta_title' => 'Hyundai Việt Nam',
                'meta_description' => 'Các mẫu xe Hyundai bán chạy tại Việt Nam.',
                'keywords' => 'hyundai, accent, santafe, creta',
                'founded_year' => 1967,
                'website' => 'https://www.hyundai.com/vn',
                'phone' => '024 9876 5432',
                'email' => 'info@hyundai.com.vn',
                'address' => 'Số 166 Phạm Văn Đồng, Cầu Giấy, Hà Nội',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'VinFast',
                'slug' => 'vinfast',
                'logo_path' => 'images/logos/vinfast.png',
                'country' => 'Vietnam',
                'description' => 'Thương hiệu xe Việt với các dòng xe điện tiên tiến.',
                'meta_title' => 'VinFast Việt Nam',
                'meta_description' => 'Dải sản phẩm ô tô điện VinFast tại Việt Nam.',
                'keywords' => 'vinfast, vf e34, vf 8, vf 9',
                'founded_year' => 2017,
                'website' => 'https://vinfastauto.com',
                'phone' => '1800 646 588',
                'email' => 'cs@vinfast.vn',
                'address' => 'Khu kinh tế Đình Vũ - Cát Hải, Hải Phòng',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Honda',
                'slug' => 'honda',
                'logo_path' => 'images/logos/honda.png',
                'country' => 'Japan',
                'description' => 'Thương hiệu Nhật Bản với các mẫu xe bền bỉ, giữ giá tốt.',
                'meta_title' => 'Honda Việt Nam',
                'meta_description' => 'Các mẫu xe Honda: City, Civic, CR-V...',
                'keywords' => 'honda, city, civic, cr-v',
                'founded_year' => 1948,
                'website' => 'https://www.honda.com.vn',
                'phone' => '024 1234 5678',
                'email' => 'contact@honda.com.vn',
                'address' => 'Xã Phúc Thắng, Phúc Yên, Vĩnh Phúc',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Mazda',
                'slug' => 'mazda',
                'logo_path' => 'images/logos/mazda.png',
                'country' => 'Japan',
                'description' => 'Thiết kế KODO cùng công nghệ SkyActiv.',
                'meta_title' => 'Mazda Việt Nam',
                'meta_description' => 'Các mẫu Mazda phổ biến: Mazda3, CX-5...',
                'keywords' => 'mazda, mazda3, cx-5',
                'founded_year' => 1920,
                'website' => 'https://mazdamotors.vn',
                'phone' => '028 1111 2222',
                'email' => 'info@mazda.vn',
                'address' => 'Số 26 Trường Chinh, Tân Bình, TP.HCM',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Kia',
                'slug' => 'kia',
                'logo_path' => 'images/logos/kia.png',
                'country' => 'South Korea',
                'description' => 'Thương hiệu Hàn Quốc, thiết kế trẻ trung.',
                'meta_title' => 'Kia Việt Nam',
                'meta_description' => 'Các mẫu Kia: Seltos, Sorento...',
                'keywords' => 'kia, seltos, sorento',
                'founded_year' => 1944,
                'website' => 'https://www.kia.com/vn',
                'phone' => '028 3333 4444',
                'email' => 'support@kia.vn',
                'address' => 'Lô C4, KCN Hiệp Phước, Nhà Bè, TP.HCM',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'name' => 'Mitsubishi',
                'slug' => 'mitsubishi',
                'logo_path' => 'images/logos/mitsubishi.png',
                'country' => 'Japan',
                'description' => 'Nổi tiếng với Xpander, Outlander.',
                'meta_title' => 'Mitsubishi Việt Nam',
                'meta_description' => 'Mitsubishi Xpander, Attrage...',
                'keywords' => 'mitsubishi, xpander, attrage',
                'founded_year' => 1870,
                'website' => 'https://www.mitsubishi-motors.com.vn',
                'phone' => '028 5555 6666',
                'email' => 'cs@mitsubishi.vn',
                'address' => 'Số 29 Song Hành, Quận 2, TP.HCM',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Ford',
                'slug' => 'ford',
                'logo_path' => 'images/logos/ford.png',
                'country' => 'USA',
                'description' => 'Bán tải Ranger, SUV Everest.',
                'meta_title' => 'Ford Việt Nam',
                'meta_description' => 'Ford Ranger, Everest...',
                'keywords' => 'ford, ranger, everest',
                'founded_year' => 1903,
                'website' => 'https://www.ford.com.vn',
                'phone' => '024 7777 8888',
                'email' => 'info@ford.com.vn',
                'address' => 'Hà Nội',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'BMW',
                'slug' => 'bmw',
                'logo_path' => 'images/logos/bmw.png',
                'country' => 'Germany',
                'description' => 'Thương hiệu xe sang đến từ Đức.',
                'meta_title' => 'BMW Việt Nam',
                'meta_description' => 'BMW 3 Series, 5 Series, X3...',
                'keywords' => 'bmw, 3 series, x3',
                'founded_year' => 1916,
                'website' => 'https://www.bmw.vn',
                'phone' => '028 9999 0000',
                'email' => 'sales@bmw.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Mercedes-Benz',
                'slug' => 'mercedes-benz',
                'logo_path' => 'images/logos/mercedes.png',
                'country' => 'Germany',
                'description' => 'Xe sang đẳng cấp: C, E, GLC...',
                'meta_title' => 'Mercedes-Benz Việt Nam',
                'meta_description' => 'C-Class, E-Class, GLC...',
                'keywords' => 'mercedes, c-class, glc',
                'founded_year' => 1926,
                'website' => 'https://www.mercedes-benz.com.vn',
                'phone' => '028 123 8888',
                'email' => 'info@mercedes.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Nissan',
                'slug' => 'nissan',
                'logo_path' => 'images/logos/nissan.png',
                'country' => 'Japan',
                'description' => 'Thương hiệu Nhật với các mẫu xe thực dụng.',
                'meta_title' => 'Nissan Việt Nam',
                'meta_description' => 'Nissan Almera, Navara...',
                'keywords' => 'nissan, almera, navara',
                'founded_year' => 1933,
                'website' => 'https://www.nissan.com.vn',
                'phone' => '028 1112 3344',
                'email' => 'info@nissan.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'Peugeot',
                'slug' => 'peugeot',
                'logo_path' => 'images/logos/peugeot.png',
                'country' => 'France',
                'description' => 'Thiết kế Pháp, nội thất tinh tế.',
                'meta_title' => 'Peugeot Việt Nam',
                'meta_description' => 'Peugeot 2008, 3008, 5008...',
                'keywords' => 'peugeot, 3008, 5008',
                'founded_year' => 1810,
                'website' => 'https://www.peugeot.vn',
                'phone' => '028 2222 3344',
                'email' => 'contact@peugeot.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Subaru',
                'slug' => 'subaru',
                'logo_path' => 'images/logos/subaru.png',
                'country' => 'Japan',
                'description' => 'Xe AWD, động cơ Boxer trứ danh.',
                'meta_title' => 'Subaru Việt Nam',
                'meta_description' => 'Subaru Forester, Outback...',
                'keywords' => 'subaru, forester, awd',
                'founded_year' => 1953,
                'website' => 'https://www.subaru.asia/vn',
                'phone' => '028 2345 6789',
                'email' => 'sales@subaru.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'Lexus',
                'slug' => 'lexus',
                'logo_path' => 'images/logos/lexus.png',
                'country' => 'Japan',
                'description' => 'Thương hiệu hạng sang của Toyota.',
                'meta_title' => 'Lexus Việt Nam',
                'meta_description' => 'Lexus RX, NX, ES...',
                'keywords' => 'lexus, rx, nx, es',
                'founded_year' => 1989,
                'website' => 'https://www.lexus.com.vn',
                'phone' => '028 5566 7788',
                'email' => 'contact@lexus.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Audi',
                'slug' => 'audi',
                'logo_path' => 'images/logos/audi.png',
                'country' => 'Germany',
                'description' => 'Xe sang công nghệ cao.',
                'meta_title' => 'Audi Việt Nam',
                'meta_description' => 'Audi A4, Q5, Q7...',
                'keywords' => 'audi, a4, q5, q7',
                'founded_year' => 1909,
                'website' => 'https://www.audi.vn',
                'phone' => '028 6677 8899',
                'email' => 'info@audi.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Volkswagen',
                'slug' => 'volkswagen',
                'logo_path' => 'images/logos/volkswagen.png',
                'country' => 'Germany',
                'description' => 'Thực dụng, bền bỉ, an toàn.',
                'meta_title' => 'Volkswagen Việt Nam',
                'meta_description' => 'VW Tiguan, Teramont...',
                'keywords' => 'volkswagen, tiguan',
                'founded_year' => 1937,
                'website' => 'https://www.vw.com.vn',
                'phone' => '028 7788 8899',
                'email' => 'contact@vw.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'name' => 'Suzuki',
                'slug' => 'suzuki',
                'logo_path' => 'images/logos/suzuki.png',
                'country' => 'Japan',
                'description' => 'Tiện dụng, tiết kiệm chi phí.',
                'meta_title' => 'Suzuki Việt Nam',
                'meta_description' => 'Ertiga, XL7...',
                'keywords' => 'suzuki, ertiga, xl7',
                'founded_year' => 1909,
                'website' => 'https://www.suzuki.com.vn',
                'phone' => '028 8899 0011',
                'email' => 'info@suzuki.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'name' => 'MG',
                'slug' => 'mg',
                'logo_path' => 'images/logos/mg.png',
                'country' => 'UK/China',
                'description' => 'Giá tốt, option phong phú.',
                'meta_title' => 'MG Việt Nam',
                'meta_description' => 'MG ZS, HS...',
                'keywords' => 'mg, zs, hs',
                'founded_year' => 1924,
                'website' => 'https://www.mgmotor.com.vn',
                'phone' => '028 9000 1122',
                'email' => 'support@mg.vn',
                'address' => 'TP. Hồ Chí Minh',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
        ];

        foreach ($brands as $data) {
            CarBrand::updateOrCreate(['name' => $data['name']], $data);
        }
    }
}


