<?php

namespace Database\Seeders;

use App\Models\CarBrand;
use Illuminate\Database\Seeder;

class CarBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $carBrands = [
            [
                'name' => 'Toyota',
                'slug' => 'toyota',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Toyota'),
                'country' => 'Nhật Bản',
                'description' => 'Hãng xe Nhật Bản với danh tiếng về độ tin cậy và tiết kiệm nhiên liệu',
                'meta_title' => 'Toyota Việt Nam - Xe hơi chính hãng',
                'meta_description' => 'Toyota Việt Nam - Hãng xe Nhật Bản với danh tiếng về độ tin cậy và tiết kiệm nhiên liệu',
                'keywords' => 'toyota, xe toyota, toyota việt nam, xe nhật bản',
                'founded_year' => 1937,
                'website' => 'https://www.toyota.com.vn',
                'phone' => '1900-1529',
                'email' => 'info@toyota.com.vn',
                'address' => 'Toyota, Aichi, Nhật Bản',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'total_models' => 10,
                'total_variants' => 25,
                'created_at' => now()->subYears(5),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'name' => 'Honda',
                'slug' => 'honda',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Honda'),
                'country' => 'Nhật Bản',
                'description' => 'Hãng xe Nhật Bản nổi tiếng với động cơ mạnh mẽ và thiết kế thể thao',
                'meta_title' => 'Honda Việt Nam - Xe hơi thể thao',
                'meta_description' => 'Honda Việt Nam - Hãng xe Nhật Bản nổi tiếng với động cơ mạnh mẽ và thiết kế thể thao',
                'keywords' => 'honda, xe honda, honda việt nam, xe thể thao',
                'founded_year' => 1948,
                'website' => 'https://www.honda.com.vn',
                'phone' => '1900-1551',
                'email' => 'info@honda.com.vn',
                'address' => 'Minato, Tokyo, Nhật Bản',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'total_models' => 8,
                'total_variants' => 20,
                'created_at' => now()->subYears(5),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'name' => 'Ford',
                'slug' => 'ford',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Ford'),
                'country' => 'Hoa Kỳ',
                'description' => 'Hãng xe Mỹ với truyền thống lâu đời và công nghệ tiên tiến',
                'meta_title' => 'Ford Việt Nam - Xe hơi Mỹ',
                'meta_description' => 'Ford Việt Nam - Hãng xe Mỹ với truyền thống lâu đời và công nghệ tiên tiến',
                'keywords' => 'ford, xe ford, ford việt nam, xe mỹ',
                'founded_year' => 1903,
                'website' => 'https://www.ford.com.vn',
                'phone' => '1900-3113',
                'email' => 'info@ford.com.vn',
                'address' => 'Dearborn, Michigan, Hoa Kỳ',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'total_models' => 6,
                'total_variants' => 15,
                'created_at' => now()->subYears(5),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'name' => 'Hyundai',
                'slug' => 'hyundai',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Hyundai'),
                'country' => 'Hàn Quốc',
                'description' => 'Hãng xe Hàn Quốc với thiết kế hiện đại và giá cả cạnh tranh',
                'meta_title' => 'Hyundai Việt Nam - Xe hơi Hàn Quốc',
                'meta_description' => 'Hyundai Việt Nam - Hãng xe Hàn Quốc với thiết kế hiện đại và giá cả cạnh tranh',
                'keywords' => 'hyundai, xe hyundai, hyundai việt nam, xe hàn quốc',
                'founded_year' => 1967,
                'website' => 'https://www.hyundai.com.vn',
                'phone' => '1900-1547',
                'email' => 'info@hyundai.com.vn',
                'address' => 'Seoul, Hàn Quốc',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
                'total_models' => 7,
                'total_variants' => 18,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(1),
            ],
            [
                'name' => 'Kia',
                'slug' => 'kia',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Kia'),
                'country' => 'Hàn Quốc',
                'description' => 'Hãng xe Hàn Quốc với thiết kế độc đáo và công nghệ tiên tiến',
                'meta_title' => 'Kia Việt Nam - Xe hơi Hàn Quốc',
                'meta_description' => 'Kia Việt Nam - Hãng xe Hàn Quốc với thiết kế độc đáo và công nghệ tiên tiến',
                'keywords' => 'kia, xe kia, kia việt nam, xe hàn quốc',
                'founded_year' => 1944,
                'website' => 'https://www.kia.com.vn',
                'phone' => '1900-1548',
                'email' => 'info@kia.com.vn',
                'address' => 'Seoul, Hàn Quốc',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 5,
                'total_models' => 6,
                'total_variants' => 14,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(1),
            ],
            [
                'name' => 'Mazda',
                'slug' => 'mazda',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Mazda'),
                'country' => 'Nhật Bản',
                'description' => 'Hãng xe Nhật Bản với triết lý thiết kế "KODO - Soul of Motion"',
                'meta_title' => 'Mazda Việt Nam - Xe hơi Nhật Bản',
                'meta_description' => 'Mazda Việt Nam - Hãng xe Nhật Bản với triết lý thiết kế "KODO - Soul of Motion"',
                'keywords' => 'mazda, xe mazda, mazda việt nam, xe nhật bản',
                'founded_year' => 1920,
                'website' => 'https://www.mazda.com.vn',
                'phone' => '1900-1552',
                'email' => 'info@mazda.com.vn',
                'address' => 'Fuchū, Hiroshima, Nhật Bản',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 6,
                'total_models' => 5,
                'total_variants' => 12,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(1),
            ],
            [
                'name' => 'Nissan',
                'slug' => 'nissan',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Nissan'),
                'country' => 'Nhật Bản',
                'description' => 'Hãng xe Nhật Bản với công nghệ tiên tiến và thiết kế hiện đại',
                'meta_title' => 'Nissan Việt Nam - Xe hơi Nhật Bản',
                'meta_description' => 'Nissan Việt Nam - Hãng xe Nhật Bản với công nghệ tiên tiến và thiết kế hiện đại',
                'keywords' => 'nissan, xe nissan, nissan việt nam, xe nhật bản',
                'founded_year' => 1933,
                'website' => 'https://www.nissan.com.vn',
                'phone' => '1900-1553',
                'email' => 'info@nissan.com.vn',
                'address' => 'Nishi-ku, Yokohama, Nhật Bản',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
                'total_models' => 4,
                'total_variants' => 8,
                'created_at' => now()->subYears(3),
                'updated_at' => now()->subMonths(1),
            ],
            [
                'name' => 'Mercedes-Benz',
                'slug' => 'mercedes-benz',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Mercedes-Benz'),
                'country' => 'Đức',
                'description' => 'Hãng xe Đức cao cấp với danh tiếng về sự sang trọng và công nghệ',
                'meta_title' => 'Mercedes-Benz Việt Nam - Xe hơi cao cấp',
                'meta_description' => 'Mercedes-Benz Việt Nam - Hãng xe Đức cao cấp với danh tiếng về sự sang trọng và công nghệ',
                'keywords' => 'mercedes-benz, xe mercedes, mercedes việt nam, xe cao cấp',
                'founded_year' => 1926,
                'website' => 'https://www.mercedes-benz.com.vn',
                'phone' => '1900-1554',
                'email' => 'info@mercedes-benz.com.vn',
                'address' => 'Stuttgart, Đức',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 8,
                'total_models' => 7,
                'total_variants' => 16,
                'created_at' => now()->subYears(5),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'name' => 'BMW',
                'slug' => 'bmw',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('BMW'),
                'country' => 'Đức',
                'description' => 'Hãng xe Đức với danh tiếng về hiệu suất và thiết kế thể thao',
                'meta_title' => 'BMW Việt Nam - Xe hơi thể thao',
                'meta_description' => 'BMW Việt Nam - Hãng xe Đức với danh tiếng về hiệu suất và thiết kế thể thao',
                'keywords' => 'bmw, xe bmw, bmw việt nam, xe thể thao',
                'founded_year' => 1916,
                'website' => 'https://www.bmw.com.vn',
                'phone' => '1900-1555',
                'email' => 'info@bmw.com.vn',
                'address' => 'Munich, Đức',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 9,
                'total_models' => 6,
                'total_variants' => 14,
                'created_at' => now()->subYears(5),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'name' => 'Audi',
                'slug' => 'audi',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Audi'),
                'country' => 'Đức',
                'description' => 'Hãng xe Đức với công nghệ quattro và thiết kế hiện đại',
                'meta_title' => 'Audi Việt Nam - Xe hơi Đức',
                'meta_description' => 'Audi Việt Nam - Hãng xe Đức với công nghệ quattro và thiết kế hiện đại',
                'keywords' => 'audi, xe audi, audi việt nam, xe đức',
                'founded_year' => 1909,
                'website' => 'https://www.audi.com.vn',
                'phone' => '1900-1556',
                'email' => 'info@audi.com.vn',
                'address' => 'Ingolstadt, Đức',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 10,
                'total_models' => 5,
                'total_variants' => 12,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'name' => 'Volkswagen',
                'slug' => 'volkswagen',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Volkswagen'),
                'country' => 'Đức',
                'description' => 'Hãng xe Đức với danh tiếng về chất lượng và độ tin cậy',
                'meta_title' => 'Volkswagen Việt Nam - Xe hơi Đức',
                'meta_description' => 'Volkswagen Việt Nam - Hãng xe Đức với danh tiếng về chất lượng và độ tin cậy',
                'keywords' => 'volkswagen, xe volkswagen, volkswagen việt nam, xe đức',
                'founded_year' => 1937,
                'website' => 'https://www.volkswagen.com.vn',
                'phone' => '1900-1557',
                'email' => 'info@volkswagen.com.vn',
                'address' => 'Wolfsburg, Đức',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
                'total_models' => 4,
                'total_variants' => 9,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(3),
            ],
            [
                'name' => 'Lexus',
                'slug' => 'lexus',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Lexus'),
                'country' => 'Nhật Bản',
                'description' => 'Thương hiệu xe cao cấp của Toyota với sự sang trọng và công nghệ tiên tiến',
                'meta_title' => 'Lexus Việt Nam - Xe hơi cao cấp',
                'meta_description' => 'Lexus Việt Nam - Thương hiệu xe cao cấp của Toyota với sự sang trọng và công nghệ tiên tiến',
                'keywords' => 'lexus, xe lexus, lexus việt nam, xe cao cấp',
                'founded_year' => 1989,
                'website' => 'https://www.lexus.com.vn',
                'phone' => '1900-1558',
                'email' => 'info@lexus.com.vn',
                'address' => 'Nagoya, Aichi, Nhật Bản',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 12,
                'total_models' => 5,
                'total_variants' => 10,
                'created_at' => now()->subYears(3),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'name' => 'VinFast',
                'slug' => 'vinfast',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('VinFast'),
                'country' => 'Việt Nam',
                'description' => 'Hãng xe Việt Nam với định hướng điện hóa và công nghệ hiện đại',
                'meta_title' => 'VinFast Việt Nam - Xe hơi Việt Nam',
                'meta_description' => 'VinFast Việt Nam - Hãng xe Việt Nam với định hướng điện hóa và công nghệ hiện đại',
                'keywords' => 'vinfast, xe vinfast, vinfast việt nam, xe việt nam',
                'founded_year' => 2017,
                'website' => 'https://www.vinfast.com.vn',
                'phone' => '1900-1559',
                'email' => 'info@vinfast.com.vn',
                'address' => 'Hà Nội, Việt Nam',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 13,
                'total_models' => 4,
                'total_variants' => 9,
                'created_at' => now()->subYears(2),
                'updated_at' => now()->subWeeks(3),
            ],
            [
                'name' => 'Porsche',
                'slug' => 'porsche',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Porsche'),
                'country' => 'Đức',
                'description' => 'Hãng xe thể thao Đức với danh tiếng về hiệu suất và thiết kế',
                'meta_title' => 'Porsche Việt Nam - Xe hơi thể thao',
                'meta_description' => 'Porsche Việt Nam - Hãng xe thể thao Đức với danh tiếng về hiệu suất và thiết kế',
                'keywords' => 'porsche, xe porsche, porsche việt nam, xe thể thao',
                'founded_year' => 1931,
                'website' => 'https://www.porsche.com.vn',
                'phone' => '1900-1560',
                'email' => 'info@porsche.com.vn',
                'address' => 'Stuttgart, Đức',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 14,
                'total_models' => 5,
                'total_variants' => 10,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(2),
            ],
            [
                'name' => 'Ferrari',
                'slug' => 'ferrari',
                'logo_path' => 'https://placehold.co/300x300/111827/ffffff?text=' . urlencode('Ferrari'),
                'country' => 'Ý',
                'description' => 'Hãng xe siêu thể thao Ý với danh tiếng về tốc độ và thiết kế',
                'meta_title' => 'Ferrari Việt Nam - Xe hơi siêu thể thao',
                'meta_description' => 'Ferrari Việt Nam - Hãng xe siêu thể thao Ý với danh tiếng về tốc độ và thiết kế',
                'keywords' => 'ferrari, xe ferrari, ferrari việt nam, xe siêu thể thao',
                'founded_year' => 1947,
                'website' => 'https://www.ferrari.com.vn',
                'phone' => '1900-1561',
                'email' => 'info@ferrari.com.vn',
                'address' => 'Maranello, Ý',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 15,
                'total_models' => 4,
                'total_variants' => 8,
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subMonths(2),
            ],
        ];

        foreach ($carBrands as $brand) {
            CarBrand::create($brand);
        }
    }
}
