<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CarModel;
use App\Models\CarBrand;

class CarModelSeeder extends Seeder
{
    public function run(): void
    {
        $toyota = CarBrand::where('slug', 'toyota')->first();
        $hyundai = CarBrand::where('slug', 'hyundai')->first();
        $vinfast = CarBrand::where('slug', 'vinfast')->first();
        $honda = CarBrand::where('slug', 'honda')->first();
        $mazda = CarBrand::where('slug', 'mazda')->first();
        $kia = CarBrand::where('slug', 'kia')->first();
        $nissan = CarBrand::where('slug', 'nissan')->first();
        $peugeot = CarBrand::where('slug', 'peugeot')->first();
        $subaru = CarBrand::where('slug', 'subaru')->first();
        $lexus = CarBrand::where('slug', 'lexus')->first();
        $audi = CarBrand::where('slug', 'audi')->first();
        $vw = CarBrand::where('slug', 'volkswagen')->first();
        $suzuki = CarBrand::where('slug', 'suzuki')->first();
        $mg = CarBrand::where('slug', 'mg')->first();

        $models = array_filter([
            $toyota ? [
                'car_brand_id' => $toyota->id,
                'name' => 'Vios',
                'slug' => null,
                'description' => 'Sedan hạng B phổ biến, bền bỉ, tiết kiệm nhiên liệu.',
                'body_type' => 'sedan',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2013,
                'production_end_year' => null,
                'generation' => 'Gen 4',
                'meta_title' => 'Toyota Vios',
                'meta_description' => 'Toyota Vios mới, tiết kiệm, ổn định.',
                'keywords' => 'vios, sedan hạng b',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $hyundai ? [
                'car_brand_id' => $hyundai->id,
                'name' => 'Santa Fe',
                'slug' => null,
                'description' => 'SUV 7 chỗ sang trọng, nhiều công nghệ.',
                'body_type' => 'suv',
                'segment' => 'full-size',
                'fuel_type' => 'diesel',
                'production_start_year' => 2018,
                'production_end_year' => null,
                'generation' => 'Gen 4',
                'meta_title' => 'Hyundai Santa Fe',
                'meta_description' => 'Hyundai Santa Fe trang bị hiện đại.',
                'keywords' => 'santafe, suv 7 cho',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $vinfast ? [
                'car_brand_id' => $vinfast->id,
                'name' => 'VF 8',
                'slug' => null,
                'description' => 'SUV điện cỡ trung, công nghệ thông minh.',
                'body_type' => 'suv',
                'segment' => 'premium',
                'fuel_type' => 'electric',
                'production_start_year' => 2022,
                'production_end_year' => null,
                'generation' => 'Gen 1',
                'meta_title' => 'VinFast VF 8',
                'meta_description' => 'VF 8 – SUV điện Việt Nam.',
                'keywords' => 'vinfast vf8, xe dien',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $honda ? [
                'car_brand_id' => $honda->id,
                'name' => 'City',
                'slug' => null,
                'description' => 'Sedan hạng B tiết kiệm, vận hành ổn định.',
                'body_type' => 'sedan',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2020,
                'production_end_year' => null,
                'generation' => 'Gen 5',
                'meta_title' => 'Honda City',
                'meta_description' => 'Honda City tiết kiệm xăng, phù hợp đô thị.',
                'keywords' => 'honda city',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $mazda ? [
                'car_brand_id' => $mazda->id,
                'name' => 'CX-5',
                'slug' => null,
                'description' => 'SUV 5 chỗ, thiết kế KODO, SkyActiv.',
                'body_type' => 'suv',
                'segment' => 'mid-size',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2017,
                'production_end_year' => null,
                'generation' => 'Gen 2',
                'meta_title' => 'Mazda CX-5',
                'meta_description' => 'Mazda CX-5 với ngôn ngữ thiết kế KODO.',
                'keywords' => 'mazda cx-5',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $kia ? [
                'car_brand_id' => $kia->id,
                'name' => 'Seltos',
                'slug' => null,
                'description' => 'SUV đô thị trẻ trung.',
                'body_type' => 'suv',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2020,
                'production_end_year' => null,
                'generation' => 'Gen 1',
                'meta_title' => 'Kia Seltos',
                'meta_description' => 'Kia Seltos năng động.',
                'keywords' => 'kia seltos',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $nissan ? [
                'car_brand_id' => $nissan->id,
                'name' => 'Almera',
                'slug' => null,
                'description' => 'Sedan hạng B, động cơ tăng áp 1.0.',
                'body_type' => 'sedan',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2020,
                'production_end_year' => null,
                'generation' => 'Gen 1',
                'meta_title' => 'Nissan Almera',
                'meta_description' => 'Nissan Almera tăng áp.',
                'keywords' => 'nissan almera',
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $nissan ? [
                'car_brand_id' => $nissan->id,
                'name' => 'Navara',
                'slug' => null,
                'description' => 'Bán tải mạnh mẽ, bền bỉ.',
                'body_type' => 'pickup',
                'segment' => 'mid-size',
                'fuel_type' => 'diesel',
                'production_start_year' => 2015,
                'production_end_year' => null,
                'generation' => 'Gen 3',
                'meta_title' => 'Nissan Navara',
                'meta_description' => 'Navara bền bỉ.',
                'keywords' => 'nissan navara',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 2,
            ] : null,
            $peugeot ? [
                'car_brand_id' => $peugeot->id,
                'name' => '3008',
                'slug' => null,
                'description' => 'SUV 5 chỗ thiết kế Pháp.',
                'body_type' => 'suv',
                'segment' => 'mid-size',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2017,
                'production_end_year' => null,
                'generation' => 'Gen 2',
                'meta_title' => 'Peugeot 3008',
                'meta_description' => 'Peugeot 3008 nội thất i-Cockpit.',
                'keywords' => 'peugeot 3008',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $peugeot ? [
                'car_brand_id' => $peugeot->id,
                'name' => '5008',
                'slug' => null,
                'description' => 'SUV 5+2 sang trọng.',
                'body_type' => 'suv',
                'segment' => 'full-size',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2017,
                'production_end_year' => null,
                'generation' => 'Gen 2',
                'meta_title' => 'Peugeot 5008',
                'meta_description' => 'Peugeot 5008 7 chỗ.',
                'keywords' => 'peugeot 5008',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 2,
            ] : null,
            $subaru ? [
                'car_brand_id' => $subaru->id,
                'name' => 'Forester',
                'slug' => null,
                'description' => 'SUV AWD, động cơ Boxer.',
                'body_type' => 'suv',
                'segment' => 'mid-size',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2018,
                'production_end_year' => null,
                'generation' => 'Gen 5',
                'meta_title' => 'Subaru Forester',
                'meta_description' => 'Forester AWD an toàn.',
                'keywords' => 'subaru forester',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $lexus ? [
                'car_brand_id' => $lexus->id,
                'name' => 'RX',
                'slug' => null,
                'description' => 'SUV hạng sang 5 chỗ.',
                'body_type' => 'suv',
                'segment' => 'premium',
                'fuel_type' => 'hybrid',
                'production_start_year' => 2020,
                'production_end_year' => null,
                'generation' => 'Gen 5',
                'meta_title' => 'Lexus RX',
                'meta_description' => 'Lexus RX sang trọng.',
                'keywords' => 'lexus rx',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => true,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $audi ? [
                'car_brand_id' => $audi->id,
                'name' => 'Q5',
                'slug' => null,
                'description' => 'SUV hạng sang công nghệ cao.',
                'body_type' => 'suv',
                'segment' => 'premium',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2017,
                'production_end_year' => null,
                'generation' => 'Gen 2',
                'meta_title' => 'Audi Q5',
                'meta_description' => 'Audi Q5 quattro.',
                'keywords' => 'audi q5',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $vw ? [
                'car_brand_id' => $vw->id,
                'name' => 'Tiguan',
                'slug' => null,
                'description' => 'SUV 5+2 thực dụng.',
                'body_type' => 'suv',
                'segment' => 'mid-size',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2017,
                'production_end_year' => null,
                'generation' => 'Gen 2',
                'meta_title' => 'Volkswagen Tiguan',
                'meta_description' => 'VW Tiguan 7 chỗ.',
                'keywords' => 'vw tiguan',
                'is_active' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $suzuki ? [
                'car_brand_id' => $suzuki->id,
                'name' => 'XL7',
                'slug' => null,
                'description' => 'MPV 7 chỗ giá tốt.',
                'body_type' => 'minivan',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2020,
                'production_end_year' => null,
                'generation' => 'Gen 1',
                'meta_title' => 'Suzuki XL7',
                'meta_description' => 'XL7 tiết kiệm chi phí.',
                'keywords' => 'suzuki xl7',
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
            $mg ? [
                'car_brand_id' => $mg->id,
                'name' => 'ZS',
                'slug' => null,
                'description' => 'SUV đô thị giá tốt.',
                'body_type' => 'suv',
                'segment' => 'compact',
                'fuel_type' => 'gasoline',
                'production_start_year' => 2019,
                'production_end_year' => null,
                'generation' => 'Gen 1',
                'meta_title' => 'MG ZS',
                'meta_description' => 'MG ZS nhiều option.',
                'keywords' => 'mg zs',
                'is_active' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_discontinued' => false,
                'sort_order' => 1,
            ] : null,
        ]);

        foreach ($models as $data) {
            CarModel::updateOrCreate([
                'car_brand_id' => $data['car_brand_id'],
                'name' => $data['name'],
            ], $data);
        }
    }
}


