<?php

namespace Database\Seeders;

use App\Models\CarSpecification;
use App\Models\CarVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSpecificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Map variant names to IDs once
        $variantIdByName = [
            'Vios G' => CarVariant::where('name', 'Vios G')->value('id'),
            'Vios E' => CarVariant::where('name', 'Vios E')->value('id'),
            'Vios G CVT' => CarVariant::where('name', 'Vios G CVT')->value('id'),
            'City G' => CarVariant::where('name', 'City G')->value('id'),
            'City RS' => CarVariant::where('name', 'City RS')->value('id'),
            'Innova G' => CarVariant::where('name', 'Innova G')->value('id'),
            'Fortuner G' => CarVariant::where('name', 'Fortuner G')->value('id'),
            'CR-V G' => CarVariant::where('name', 'CR-V G')->value('id'),
            'Ranger XLT' => CarVariant::where('name', 'Ranger XLT')->value('id'),
            'Accent G' => CarVariant::where('name', 'Accent G')->value('id'),
            'C-Class C200' => CarVariant::where('name', 'C-Class C200')->value('id'),
            'GLC 200' => CarVariant::where('name', 'GLC 200')->value('id'),
            '3 Series 320i' => CarVariant::where('name', '3 Series 320i')->value('id'),
            '3 Series 330i M Sport' => CarVariant::where('name', '3 Series 330i M Sport')->value('id'),
            'VF 8 Plus' => CarVariant::where('name', 'VF 8 Plus')->value('id'),
            'Corolla Cross G' => CarVariant::where('name', 'Corolla Cross G')->value('id'),
            'VF 9 Eco' => CarVariant::where('name', 'VF 9 Eco')->value('id'),
            'Corolla Altis 1.8HEV' => CarVariant::where('name', 'Corolla Altis 1.8HEV')->value('id'),
            'Camry 2.5HV' => CarVariant::where('name', 'Camry 2.5HV')->value('id'),
            'Creta Premium' => CarVariant::where('name', 'Creta Premium')->value('id'),
            'Carnival Signature 7' => CarVariant::where('name', 'Carnival Signature 7')->value('id'),
            'CX-5 2.0 Premium' => CarVariant::where('name', 'CX-5 2.0 Premium')->value('id'),
            'X5 xDrive40i' => CarVariant::where('name', 'X5 xDrive40i')->value('id'),
            'Q5 45 TFSI quattro' => CarVariant::where('name', 'Q5 45 TFSI quattro')->value('id'),
        ];

        $now = now();
        $t = fn($days) => $now->copy()->subDays($days)->format('Y-m-d H:i:s');

        $specifications = [
            // Toyota Vios G Specifications
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(180),
                'updated_at' => $t(90),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '107',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,000 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(180),
                'updated_at' => $t(90),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'engine',
                'spec_name' => 'Mô-men xoắn tối đa',
                'spec_value' => '140',
                'unit' => 'Nm',
                'description' => 'Mô-men xoắn tối đa tại 4,200 rpm',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'torque',
                'sort_order' => 3,
                'created_at' => $t(180),
                'updated_at' => $t(90),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'transmission',
                'spec_name' => 'Hộp số',
                'spec_value' => 'Số tự động',
                'unit' => null,
                'description' => 'Hộp số tự động 6 cấp',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'transmission',
                'sort_order' => 4,
                'created_at' => $t(180),
                'updated_at' => $t(90),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'performance',
                'spec_name' => 'Tốc độ tối đa',
                'spec_value' => '180',
                'unit' => 'km/h',
                'description' => 'Tốc độ tối đa',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'top_speed',
                'sort_order' => 5,
                'created_at' => $t(175),
                'updated_at' => $t(88),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'performance',
                'spec_name' => 'Tăng tốc 0-100 km/h',
                'spec_value' => '12.5',
                'unit' => 'giây',
                'description' => 'Thời gian tăng tốc từ 0-100 km/h',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'acceleration_0_100',
                'sort_order' => 6,
                'created_at' => $t(175),
                'updated_at' => $t(88),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'category' => 'fuel',
                'spec_name' => 'Tiêu thụ nhiên liệu',
                'spec_value' => '5.8',
                'unit' => 'L/100km',
                'description' => 'Tiêu thụ nhiên liệu trung bình',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'consumption_combined',
                'sort_order' => 7,
                'created_at' => $t(170),
                'updated_at' => $t(85),
            ],

            // Honda City G Specifications
            [
                'car_variant_id' => $variantIdByName['City G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC i-VTEC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với công nghệ i-VTEC',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(150),
                'updated_at' => $t(75),
            ],
            [
                'car_variant_id' => $variantIdByName['City G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '119',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,600 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(150),
                'updated_at' => $t(75),
            ],
            [
                'car_variant_id' => $variantIdByName['City G'],
                'category' => 'transmission',
                'spec_name' => 'Hộp số',
                'spec_value' => 'Số tự động',
                'unit' => null,
                'description' => 'Hộp số tự động CVT',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'transmission',
                'sort_order' => 3,
                'created_at' => $t(150),
                'updated_at' => $t(75),
            ],

            // Toyota Fortuner G Specifications
            [
                'car_variant_id' => $variantIdByName['Fortuner G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.8L 4-cylinder DOHC Turbo Diesel',
                'unit' => null,
                'description' => 'Động cơ diesel 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(130),
                'updated_at' => $t(65),
            ],
            [
                'car_variant_id' => $variantIdByName['Fortuner G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '204',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 3,400 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(130),
                'updated_at' => $t(65),
            ],
            [
                'car_variant_id' => $variantIdByName['Fortuner G'],
                'category' => 'engine',
                'spec_name' => 'Mô-men xoắn tối đa',
                'spec_value' => '500',
                'unit' => 'Nm',
                'description' => 'Mô-men xoắn tối đa tại 1,600-2,400 rpm',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'torque',
                'sort_order' => 3,
                'created_at' => $t(130),
                'updated_at' => $t(65),
            ],

            // Mercedes-Benz C-Class C200 Specifications
            [
                'car_variant_id' => $variantIdByName['C-Class C200'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(120),
                'updated_at' => $t(60),
            ],
            [
                'car_variant_id' => $variantIdByName['C-Class C200'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '197',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,500 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(120),
                'updated_at' => $t(60),
            ],
            [
                'car_variant_id' => $variantIdByName['C-Class C200'],
                'category' => 'performance',
                'spec_name' => 'Tăng tốc 0-100 km/h',
                'spec_value' => '7.3',
                'unit' => 'giây',
                'description' => 'Thời gian tăng tốc từ 0-100 km/h',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'acceleration_0_100',
                'sort_order' => 3,
                'created_at' => $t(115),
                'updated_at' => $t(57),
            ],

            // Toyota Vios E Specifications
            [
                'car_variant_id' => $variantIdByName['Vios E'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(110),
                'updated_at' => $t(55),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios E'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '107',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,000 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(110),
                'updated_at' => $t(55),
            ],

            // Toyota Vios G CVT Specifications
            [
                'car_variant_id' => $variantIdByName['Vios G CVT'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(105),
                'updated_at' => $t(52),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G CVT'],
                'category' => 'transmission',
                'spec_name' => 'Hộp số',
                'spec_value' => 'CVT',
                'unit' => null,
                'description' => 'Hộp số CVT tiết kiệm nhiên liệu',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'transmission',
                'sort_order' => 2,
                'created_at' => $t(105),
                'updated_at' => $t(52),
            ],

            // Honda City RS Specifications
            [
                'car_variant_id' => $variantIdByName['City RS'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC i-VTEC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với công nghệ i-VTEC',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(100),
                'updated_at' => $t(50),
            ],
            [
                'car_variant_id' => $variantIdByName['City RS'],
                'category' => 'performance',
                'spec_name' => 'Tăng tốc 0-100 km/h',
                'spec_value' => '11.5',
                'unit' => 'giây',
                'description' => 'Thời gian tăng tốc từ 0-100 km/h',
                'is_important' => true,
                'is_highlighted' => false,
                'spec_code' => 'acceleration_0_100',
                'sort_order' => 2,
                'created_at' => $t(98),
                'updated_at' => $t(49),
            ],

            // Toyota Innova G Specifications
            [
                'car_variant_id' => $variantIdByName['Innova G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(95),
                'updated_at' => $t(47),
            ],
            [
                'car_variant_id' => $variantIdByName['Innova G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '139',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,100 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(95),
                'updated_at' => $t(47),
            ],

            // Honda CR-V G Specifications
            [
                'car_variant_id' => $variantIdByName['CR-V G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(90),
                'updated_at' => $t(45),
            ],
            [
                'car_variant_id' => $variantIdByName['CR-V G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '188',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,600 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(90),
                'updated_at' => $t(45),
            ],

            // Ford Ranger XLT Specifications
            [
                'car_variant_id' => $variantIdByName['Ranger XLT'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Bi-Turbo Diesel',
                'unit' => null,
                'description' => 'Động cơ diesel 4 xi-lanh với bi-turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(85),
                'updated_at' => $t(42),
            ],
            [
                'car_variant_id' => $variantIdByName['Ranger XLT'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '213',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 3,750 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(85),
                'updated_at' => $t(42),
            ],

            // Hyundai Accent G Specifications
            [
                'car_variant_id' => $variantIdByName['Accent G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.4L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(82),
                'updated_at' => $t(41),
            ],
            [
                'car_variant_id' => $variantIdByName['Accent G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '100',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,000 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(82),
                'updated_at' => $t(41),
            ],

            // Mercedes-Benz GLC 200 Specifications
            [
                'car_variant_id' => $variantIdByName['GLC 200'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(77),
                'updated_at' => $t(38),
            ],
            [
                'car_variant_id' => $variantIdByName['GLC 200'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '197',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,500 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(77),
                'updated_at' => $t(38),
            ],

            // BMW 3 Series 320i Specifications
            [
                'car_variant_id' => $variantIdByName['3 Series 320i'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(72),
                'updated_at' => $t(36),
            ],
            [
                'car_variant_id' => $variantIdByName['3 Series 320i'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '170',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,500 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(72),
                'updated_at' => $t(36),
            ],

            // BMW 3 Series 330i M Sport Specifications
            [
                'car_variant_id' => $variantIdByName['3 Series 330i M Sport'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(67),
                'updated_at' => $t(33),
            ],
            [
                'car_variant_id' => $variantIdByName['3 Series 330i M Sport'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '258',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,000 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(67),
                'updated_at' => $t(33),
            ],

            // VinFast VF 8 Plus Specifications
            [
                'car_variant_id' => $variantIdByName['VF 8 Plus'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => 'Động cơ điện kép',
                'unit' => null,
                'description' => 'Hệ thống động cơ điện kép AWD',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(62),
                'updated_at' => $t(31),
            ],
            [
                'car_variant_id' => $variantIdByName['VF 8 Plus'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '402',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tổng hợp',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(62),
                'updated_at' => $t(31),
            ],

            // Toyota Corolla Cross G Specifications
            [
                'car_variant_id' => $variantIdByName['Corolla Cross G'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.8L 4-cylinder Hybrid',
                'unit' => null,
                'description' => 'Động cơ hybrid kết hợp xăng và điện',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(57),
                'updated_at' => $t(28),
            ],
            [
                'car_variant_id' => $variantIdByName['Corolla Cross G'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '122',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tổng hợp',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(57),
                'updated_at' => $t(28),
            ],

            // VinFast VF 9 Eco Specifications
            [
                'car_variant_id' => $variantIdByName['VF 9 Eco'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => 'Động cơ điện kép',
                'unit' => null,
                'description' => 'Hệ thống động cơ điện kép AWD',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(52),
                'updated_at' => $t(26),
            ],
            [
                'car_variant_id' => $variantIdByName['VF 9 Eco'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '402',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tổng hợp',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(52),
                'updated_at' => $t(26),
            ],

            // Toyota Corolla Altis 1.8HEV Specifications
            [
                'car_variant_id' => $variantIdByName['Corolla Altis 1.8HEV'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.8L 4-cylinder Hybrid',
                'unit' => null,
                'description' => 'Động cơ hybrid kết hợp xăng và điện',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(47),
                'updated_at' => $t(23),
            ],
            [
                'car_variant_id' => $variantIdByName['Corolla Altis 1.8HEV'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '122',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tổng hợp',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(47),
                'updated_at' => $t(23),
            ],

            // Toyota Camry 2.5HV Specifications
            [
                'car_variant_id' => $variantIdByName['Camry 2.5HV'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.5L 4-cylinder Hybrid',
                'unit' => null,
                'description' => 'Động cơ hybrid kết hợp xăng và điện',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(42),
                'updated_at' => $t(21),
            ],
            [
                'car_variant_id' => $variantIdByName['Camry 2.5HV'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '218',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tổng hợp',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(42),
                'updated_at' => $t(21),
            ],

            // Hyundai Creta Premium Specifications
            [
                'car_variant_id' => $variantIdByName['Creta Premium'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '1.5L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(37),
                'updated_at' => $t(18),
            ],
            [
                'car_variant_id' => $variantIdByName['Creta Premium'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '115',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,300 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(37),
                'updated_at' => $t(18),
            ],

            // Kia Carnival Signature 7 Specifications
            [
                'car_variant_id' => $variantIdByName['Carnival Signature 7'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '3.5L 6-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 6 xi-lanh V6',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(32),
                'updated_at' => $t(16),
            ],
            [
                'car_variant_id' => $variantIdByName['Carnival Signature 7'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '272',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,400 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(32),
                'updated_at' => $t(16),
            ],

            // Mazda CX-5 2.0 Premium Specifications
            [
                'car_variant_id' => $variantIdByName['CX-5 2.0 Premium'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder DOHC',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh thẳng hàng',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(27),
                'updated_at' => $t(13),
            ],
            [
                'car_variant_id' => $variantIdByName['CX-5 2.0 Premium'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '150',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 6,000 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(27),
                'updated_at' => $t(13),
            ],

            // BMW X5 xDrive40i Specifications
            [
                'car_variant_id' => $variantIdByName['X5 xDrive40i'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '3.0L 6-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 6 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(22),
                'updated_at' => $t(11),
            ],
            [
                'car_variant_id' => $variantIdByName['X5 xDrive40i'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '340',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,500 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(22),
                'updated_at' => $t(11),
            ],

            // Audi Q5 45 TFSI quattro Specifications
            [
                'car_variant_id' => $variantIdByName['Q5 45 TFSI quattro'],
                'category' => 'engine',
                'spec_name' => 'Loại động cơ',
                'spec_value' => '2.0L 4-cylinder Turbo',
                'unit' => null,
                'description' => 'Động cơ xăng 4 xi-lanh với turbo',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'engine_type',
                'sort_order' => 1,
                'created_at' => $t(17),
                'updated_at' => $t(8),
            ],
            [
                'car_variant_id' => $variantIdByName['Q5 45 TFSI quattro'],
                'category' => 'engine',
                'spec_name' => 'Công suất tối đa',
                'spec_value' => '265',
                'unit' => 'hp',
                'description' => 'Công suất tối đa tại 5,250 rpm',
                'is_important' => true,
                'is_highlighted' => true,
                'spec_code' => 'power_output',
                'sort_order' => 2,
                'created_at' => $t(17),
                'updated_at' => $t(8),
            ]
        ];

        DB::table('car_specifications')->truncate();
        CarSpecification::insert($specifications);
    }
}
