<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\CarVariantColor;

class CarVariantColorSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        
        $colors = [
            // Toyota Vios G
            [
                'car_variant_id' => 1,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => '040',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 1,
                'color_name' => 'Đen bóng',
                'color_code' => '202',
                'hex_code' => '#000000',
                'rgb_code' => '0,0,0',
                'color_type' => 'solid',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu đen bóng thể thao',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Toyota Vios E
            [
                'car_variant_id' => 2,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => '040',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 2,
                'color_name' => 'Xám bạc',
                'color_code' => '1F7',
                'hex_code' => '#C0C0C0',
                'rgb_code' => '192,192,192',
                'color_type' => 'metallic',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu xám bạc hiện đại',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Honda City RS
            [
                'car_variant_id' => 3,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => 'NH-883P',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 3,
                'color_name' => 'Đỏ thể thao',
                'color_code' => 'R-513M',
                'hex_code' => '#FF0000',
                'rgb_code' => '255,0,0',
                'color_type' => 'solid',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu đỏ thể thao nổi bật',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Honda City G
            [
                'car_variant_id' => 4,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => 'NH-883P',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 4,
                'color_name' => 'Xanh dương',
                'color_code' => 'B-537M',
                'hex_code' => '#0066CC',
                'rgb_code' => '0,102,204',
                'color_type' => 'metallic',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu xanh dương hiện đại',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Toyota Corolla Altis 1.8HEV
            [
                'car_variant_id' => 5,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => '040',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 5,
                'color_name' => 'Đen bóng',
                'color_code' => '202',
                'hex_code' => '#000000',
                'rgb_code' => '0,0,0',
                'color_type' => 'solid',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu đen bóng thể thao',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Toyota Camry 2.5HV
            [
                'car_variant_id' => 6,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => '040',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 6,
                'color_name' => 'Xám bạc',
                'color_code' => '1F7',
                'hex_code' => '#C0C0C0',
                'rgb_code' => '192,192,192',
                'color_type' => 'metallic',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu xám bạc hiện đại',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Mercedes GLC 200
            [
                'car_variant_id' => 7,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => '799',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 7,
                'color_name' => 'Đen Obsidian',
                'color_code' => '197',
                'hex_code' => '#000000',
                'rgb_code' => '0,0,0',
                'color_type' => 'solid',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu đen Obsidian sang trọng',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // BMW 3 Series 330i M Sport
            [
                'car_variant_id' => 8,
                'color_name' => 'Trắng Alpine',
                'color_code' => '300',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'solid',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng Alpine thể thao',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 8,
                'color_name' => 'Xanh Portimao',
                'color_code' => 'C3Z',
                'hex_code' => '#1E3A8A',
                'rgb_code' => '30,58,138',
                'color_type' => 'metallic',
                'availability' => 'optional',
                'price_adjustment' => 5000000,
                'is_free' => false,
                'description' => 'Màu xanh Portimao độc quyền',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // VinFast VF 9 Eco
            [
                'car_variant_id' => 9,
                'color_name' => 'Trắng ngọc trai',
                'color_code' => 'VF-WHITE',
                'hex_code' => '#FFFFFF',
                'rgb_code' => '255,255,255',
                'color_type' => 'pearlescent',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu trắng ngọc trai cao cấp',
                'is_popular' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => 9,
                'color_name' => 'Xanh VinFast',
                'color_code' => 'VF-BLUE',
                'hex_code' => '#0066CC',
                'rgb_code' => '0,102,204',
                'color_type' => 'metallic',
                'availability' => 'standard',
                'price_adjustment' => 0,
                'is_free' => true,
                'description' => 'Màu xanh VinFast độc quyền',
                'is_popular' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        
        DB::table('car_variant_colors')->truncate();
        CarVariantColor::insert($colors);
    }
}
