<?php

namespace Database\Seeders;

use App\Models\CarVariantImage;
use App\Models\CarVariant;
use App\Models\CarVariantColor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
 

class CarVariantImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $variants = CarVariant::with('carModel.carBrand')->get();
        $variantColors = CarVariantColor::all();
        $now = now();

        $images = [
            // Toyota Vios G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios G front'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios G front'),
                'alt_text' => 'Toyota Vios G - Góc nhìn phía trước',
                'title' => 'Toyota Vios G - Thiết kế hiện đại',
                'description' => 'Góc nhìn phía trước của Toyota Vios G với thiết kế hiện đại và sang trọng',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => true,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios G interior'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios G interior'),
                'alt_text' => 'Toyota Vios G - Nội thất',
                'title' => 'Toyota Vios G - Nội thất sang trọng',
                'description' => 'Nội thất Toyota Vios G với thiết kế sang trọng và tiện nghi',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Vios E Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios E front'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios E front'),
                'alt_text' => 'Toyota Vios E - Góc nhìn phía trước',
                'title' => 'Toyota Vios E - Thiết kế cơ bản',
                'description' => 'Góc nhìn phía trước của Toyota Vios E với thiết kế cơ bản và tiết kiệm',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => true,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios E interior'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Toyota Vios E interior'),
                'alt_text' => 'Toyota Vios E - Nội thất',
                'title' => 'Toyota Vios E - Nội thất cơ bản',
                'description' => 'Nội thất Toyota Vios E với thiết kế cơ bản và tiện nghi',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda City G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Honda City G front'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Honda City G front'),
                'alt_text' => 'Honda City G - Góc nhìn phía trước',
                'title' => 'Honda City G - Thiết kế thể thao',
                'description' => 'Góc nhìn phía trước của Honda City G với thiết kế thể thao và năng động',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => true,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'image_path' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Honda City G interior'),
                'image_url' => 'https://placehold.co/1200x800/111827/ffffff?text=' . urlencode('Honda City G interior'),
                'alt_text' => 'Honda City G - Nội thất',
                'title' => 'Honda City G - Nội thất hiện đại',
                'description' => 'Nội thất Honda City G với thiết kế hiện đại và công nghệ tiên tiến',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda City RS Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'image_path' => 'car-variants/honda-city-rs-front.jpg',
                'image_url' => 'car-variants/honda-city-rs-front.jpg',
                'alt_text' => 'Honda City RS - Góc nhìn phía trước',
                'title' => 'Honda City RS - Thiết kế thể thao cao cấp',
                'description' => 'Góc nhìn phía trước của Honda City RS với thiết kế thể thao cao cấp',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'image_path' => 'car-variants/honda-city-rs-interior.jpg',
                'image_url' => 'car-variants/honda-city-rs-interior.jpg',
                'alt_text' => 'Honda City RS - Nội thất',
                'title' => 'Honda City RS - Nội thất thể thao',
                'description' => 'Nội thất Honda City RS với thiết kế thể thao và cao cấp',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Vios G CVT Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G CVT')->first()->id,
                'image_path' => 'car-variants/toyota-vios-g-cvt-front.jpg',
                'image_url' => 'car-variants/toyota-vios-g-cvt-front.jpg',
                'alt_text' => 'Toyota Vios G CVT - Góc nhìn phía trước',
                'title' => 'Toyota Vios G CVT - Hộp số CVT',
                'description' => 'Góc nhìn phía trước của Toyota Vios G CVT với thiết kế hiện đại',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G CVT')->first()->id,
                'image_path' => 'car-variants/toyota-vios-g-cvt-interior.jpg',
                'image_url' => 'car-variants/toyota-vios-g-cvt-interior.jpg',
                'alt_text' => 'Toyota Vios G CVT - Nội thất',
                'title' => 'Toyota Vios G CVT - Nội thất hiện đại',
                'description' => 'Nội thất Toyota Vios G CVT với thiết kế hiện đại và tiện nghi',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Innova G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'image_path' => 'car-variants/toyota-innova-g-front.jpg',
                'image_url' => 'car-variants/toyota-innova-g-front.jpg',
                'alt_text' => 'Toyota Innova G - Góc nhìn phía trước',
                'title' => 'Toyota Innova G - Thiết kế đa dụng',
                'description' => 'Góc nhìn phía trước của Toyota Innova G với thiết kế đa dụng và hiện đại',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'image_path' => 'car-variants/toyota-innova-g-interior.jpg',
                'image_url' => 'car-variants/toyota-innova-g-interior.jpg',
                'alt_text' => 'Toyota Innova G - Nội thất',
                'title' => 'Toyota Innova G - Nội thất đa dụng',
                'description' => 'Nội thất Toyota Innova G với thiết kế đa dụng cho gia đình',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Fortuner G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Fortuner G')->first()->id,
                'image_path' => 'car-variants/toyota-fortuner-g-front.jpg',
                'image_url' => 'car-variants/toyota-fortuner-g-front.jpg',
                'alt_text' => 'Toyota Fortuner G - Góc nhìn phía trước',
                'title' => 'Toyota Fortuner G - SUV 7 chỗ',
                'description' => 'Góc nhìn phía trước của Toyota Fortuner G với thiết kế mạnh mẽ',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Fortuner G')->first()->id,
                'image_path' => 'car-variants/toyota-fortuner-g-interior.jpg',
                'image_url' => 'car-variants/toyota-fortuner-g-interior.jpg',
                'alt_text' => 'Toyota Fortuner G - Nội thất',
                'title' => 'Toyota Fortuner G - Nội thất rộng rãi',
                'description' => 'Nội thất Toyota Fortuner G rộng rãi và tiện nghi',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda CR-V G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'CR-V G')->first()->id,
                'image_path' => 'car-variants/honda-crv-g-front.jpg',
                'image_url' => 'car-variants/honda-crv-g-front.jpg',
                'alt_text' => 'Honda CR-V G - Góc nhìn phía trước',
                'title' => 'Honda CR-V G - SUV hiện đại',
                'description' => 'Góc nhìn phía trước của Honda CR-V G với thiết kế hiện đại',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'CR-V G')->first()->id,
                'image_path' => 'car-variants/honda-crv-g-interior.jpg',
                'image_url' => 'car-variants/honda-crv-g-interior.jpg',
                'alt_text' => 'Honda CR-V G - Nội thất',
                'title' => 'Honda CR-V G - Nội thất hiện đại',
                'description' => 'Nội thất Honda CR-V G với thiết kế hiện đại và công nghệ tiên tiến',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Ford Ranger XLT Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'image_path' => 'car-variants/ford-ranger-xlt-front.jpg',
                'image_url' => 'car-variants/ford-ranger-xlt-front.jpg',
                'alt_text' => 'Ford Ranger XLT - Góc nhìn phía trước',
                'title' => 'Ford Ranger XLT - Thiết kế mạnh mẽ',
                'description' => 'Góc nhìn phía trước của Ford Ranger XLT với thiết kế mạnh mẽ và nam tính',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'image_path' => 'car-variants/ford-ranger-xlt-interior.jpg',
                'image_url' => 'car-variants/ford-ranger-xlt-interior.jpg',
                'alt_text' => 'Ford Ranger XLT - Nội thất',
                'title' => 'Ford Ranger XLT - Nội thất hiện đại',
                'description' => 'Nội thất Ford Ranger XLT với thiết kế hiện đại và công nghệ tiên tiến',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Hyundai Accent G Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'image_path' => 'car-variants/hyundai-accent-g-front.jpg',
                'image_url' => 'car-variants/hyundai-accent-g-front.jpg',
                'alt_text' => 'Hyundai Accent G - Góc nhìn phía trước',
                'title' => 'Hyundai Accent G - Thiết kế hiện đại',
                'description' => 'Góc nhìn phía trước của Hyundai Accent G với thiết kế hiện đại',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'image_path' => 'car-variants/hyundai-accent-g-interior.jpg',
                'image_url' => 'car-variants/hyundai-accent-g-interior.jpg',
                'alt_text' => 'Hyundai Accent G - Nội thất',
                'title' => 'Hyundai Accent G - Nội thất hiện đại',
                'description' => 'Nội thất Hyundai Accent G với thiết kế hiện đại và tiện nghi',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mercedes-Benz C-Class C200 Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'image_path' => 'car-variants/mercedes-c-class-c200-front.jpg',
                'image_url' => 'car-variants/mercedes-c-class-c200-front.jpg',
                'alt_text' => 'Mercedes-Benz C-Class C200 - Góc nhìn phía trước',
                'title' => 'Mercedes-Benz C-Class C200 - Sang trọng',
                'description' => 'Góc nhìn phía trước của Mercedes-Benz C-Class C200 với thiết kế sang trọng',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'image_path' => 'car-variants/mercedes-c-class-c200-interior.jpg',
                'image_url' => 'car-variants/mercedes-c-class-c200-interior.jpg',
                'alt_text' => 'Mercedes-Benz C-Class C200 - Nội thất',
                'title' => 'Mercedes-Benz C-Class C200 - Nội thất cao cấp',
                'description' => 'Nội thất Mercedes-Benz C-Class C200 với thiết kế cao cấp và sang trọng',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BMW 3 Series 320i Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'image_path' => 'car-variants/bmw-3-series-320i-front.jpg',
                'image_url' => 'car-variants/bmw-3-series-320i-front.jpg',
                'alt_text' => 'BMW 3 Series 320i - Góc nhìn phía trước',
                'title' => 'BMW 3 Series 320i - Thể thao',
                'description' => 'Góc nhìn phía trước của BMW 3 Series 320i với thiết kế thể thao',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'image_path' => 'car-variants/bmw-3-series-320i-interior.jpg',
                'image_url' => 'car-variants/bmw-3-series-320i-interior.jpg',
                'alt_text' => 'BMW 3 Series 320i - Nội thất',
                'title' => 'BMW 3 Series 320i - Nội thất thể thao',
                'description' => 'Nội thất BMW 3 Series 320i với thiết kế thể thao và hiện đại',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // VinFast VF 8 Plus Images
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'VF 8 Plus')->first()->id,
                'image_path' => 'car-variants/vinfast-vf8-plus-front.jpg',
                'image_url' => 'car-variants/vinfast-vf8-plus-front.jpg',
                'alt_text' => 'VinFast VF 8 Plus - Góc nhìn phía trước',
                'title' => 'VinFast VF 8 Plus - SUV điện',
                'description' => 'Góc nhìn phía trước của VinFast VF 8 Plus với thiết kế SUV điện hiện đại',
                'image_type' => 'exterior',
                'angle' => 'front',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'VF 8 Plus')->first()->id,
                'image_path' => 'car-variants/vinfast-vf8-plus-interior.jpg',
                'image_url' => 'car-variants/vinfast-vf8-plus-interior.jpg',
                'alt_text' => 'VinFast VF 8 Plus - Nội thất',
                'title' => 'VinFast VF 8 Plus - Nội thất hiện đại',
                'description' => 'Nội thất VinFast VF 8 Plus với thiết kế hiện đại và công nghệ tiên tiến',
                'image_type' => 'interior',
                'angle' => 'dashboard',
                'width' => 1200,
                'height' => 800,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_active' => true,
                'is_main' => false,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ];
        // Gallery images per color variants
        $colorImages = [
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Vios G')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Trắng ngọc trai'),
                'alt_text' => 'Vios G - Trắng ngọc trai',
                'title' => 'Vios G - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Vios G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'C-Class C200')->first()->id)->where('color_name', 'Đen bóng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('C200 - Đen bóng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('C200 - Đen bóng'),
                'alt_text' => 'C200 - Đen bóng',
                'title' => 'C200 - Màu Đen bóng',
                'description' => 'Ảnh màu Đen bóng của C-Class C200',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Vios G')->first()->id)->where('color_name', 'Đen bóng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Đen bóng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Đen bóng'),
                'alt_text' => 'Vios G - Đen bóng',
                'title' => 'Vios G - Màu Đen bóng',
                'description' => 'Ảnh màu Đen bóng của Vios G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Vios G')->first()->id)->where('color_name', 'Bạc kim loại')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Bạc kim loại'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios G - Bạc kim loại'),
                'alt_text' => 'Vios G - Bạc kim loại',
                'title' => 'Vios G - Màu Bạc kim loại',
                'description' => 'Ảnh màu Bạc kim loại của Vios G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Vios E colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Vios E')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios E - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios E - Trắng ngọc trai'),
                'alt_text' => 'Vios E - Trắng ngọc trai',
                'title' => 'Vios E - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Vios E',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Vios E')->first()->id)->where('color_name', 'Xanh dương')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios E - Xanh dương'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Vios E - Xanh dương'),
                'alt_text' => 'Vios E - Xanh dương',
                'title' => 'Vios E - Màu Xanh dương',
                'description' => 'Ảnh màu Xanh dương của Vios E',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // City G colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'City G')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City G - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City G - Trắng ngọc trai'),
                'alt_text' => 'City G - Trắng ngọc trai',
                'title' => 'City G - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của City G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'City G')->first()->id)->where('color_name', 'Đỏ thể thao')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City G - Đỏ thể thao'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City G - Đỏ thể thao'),
                'alt_text' => 'City G - Đỏ thể thao',
                'title' => 'City G - Màu Đỏ thể thao',
                'description' => 'Ảnh màu Đỏ thể thao của City G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // City RS colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'City RS')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City RS - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City RS - Trắng ngọc trai'),
                'alt_text' => 'City RS - Trắng ngọc trai',
                'title' => 'City RS - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của City RS',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'City RS')->first()->id)->where('color_name', 'Đỏ thể thao')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City RS - Đỏ thể thao'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('City RS - Đỏ thể thao'),
                'alt_text' => 'City RS - Đỏ thể thao',
                'title' => 'City RS - Màu Đỏ thể thao',
                'description' => 'Ảnh màu Đỏ thể thao của City RS',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Innova G colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Innova G')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Innova G - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Innova G - Trắng ngọc trai'),
                'alt_text' => 'Innova G - Trắng ngọc trai',
                'title' => 'Innova G - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Innova G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Innova G')->first()->id)->where('color_name', 'Bạc kim loại')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Innova G - Bạc kim loại'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Innova G - Bạc kim loại'),
                'alt_text' => 'Innova G - Bạc kim loại',
                'title' => 'Innova G - Màu Bạc kim loại',
                'description' => 'Ảnh màu Bạc kim loại của Innova G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Ranger XLT colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Ranger XLT')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Ranger XLT - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Ranger XLT - Trắng ngọc trai'),
                'alt_text' => 'Ranger XLT - Trắng ngọc trai',
                'title' => 'Ranger XLT - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Ranger XLT',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Ranger XLT')->first()->id)->where('color_name', 'Xanh rừng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Ranger XLT - Xanh rừng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Ranger XLT - Xanh rừng'),
                'alt_text' => 'Ranger XLT - Xanh rừng',
                'title' => 'Ranger XLT - Màu Xanh rừng',
                'description' => 'Ảnh màu Xanh rừng của Ranger XLT',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Accent G colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Accent G')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Accent G - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Accent G - Trắng ngọc trai'),
                'alt_text' => 'Accent G - Trắng ngọc trai',
                'title' => 'Accent G - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Accent G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Accent G')->first()->id)->where('color_name', 'Xanh dương')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Accent G - Xanh dương'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Accent G - Xanh dương'),
                'alt_text' => 'Accent G - Xanh dương',
                'title' => 'Accent G - Màu Xanh dương',
                'description' => 'Ảnh màu Xanh dương của Accent G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // C-Class C200 Trắng ngọc trai
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'C-Class C200')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('C200 - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('C200 - Trắng ngọc trai'),
                'alt_text' => 'C200 - Trắng ngọc trai',
                'title' => 'C200 - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của C-Class C200',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 3 Series 320i colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', '3 Series 320i')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('320i - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('320i - Trắng ngọc trai'),
                'alt_text' => '320i - Trắng ngọc trai',
                'title' => '320i - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của 320i',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', '3 Series 320i')->first()->id)->where('color_name', 'Xanh BMW')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('320i - Xanh BMW'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('320i - Xanh BMW'),
                'alt_text' => '320i - Xanh BMW',
                'title' => '320i - Màu Xanh BMW',
                'description' => 'Ảnh màu Xanh BMW của 320i',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // CR-V G colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'CR-V G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'CR-V G')->first()->id)->where('color_name', 'Đen bóng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('CR-V G - Đen bóng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('CR-V G - Đen bóng'),
                'alt_text' => 'CR-V G - Đen bóng',
                'title' => 'CR-V G - Màu Đen bóng',
                'description' => 'Ảnh màu Đen bóng của CR-V G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'CR-V G')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'CR-V G')->first()->id)->where('color_name', 'Xanh đậm')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('CR-V G - Xanh đậm'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('CR-V G - Xanh đậm'),
                'alt_text' => 'CR-V G - Xanh đậm',
                'title' => 'CR-V G - Màu Xanh đậm',
                'description' => 'Ảnh màu Xanh đậm của CR-V G',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Camry 2.5HV colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Camry 2.5HV')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Trắng ngọc trai'),
                'alt_text' => 'Camry 2.5HV - Trắng ngọc trai',
                'title' => 'Camry 2.5HV - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Camry 2.5HV',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Camry 2.5HV')->first()->id)->where('color_name', 'Bạc kim loại')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Bạc kim loại'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Bạc kim loại'),
                'alt_text' => 'Camry 2.5HV - Bạc kim loại',
                'title' => 'Camry 2.5HV - Màu Bạc kim loại',
                'description' => 'Ảnh màu Bạc kim loại của Camry 2.5HV',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Camry 2.5HV')->first()->id)->where('color_name', 'Đen bóng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Đen bóng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Camry 2.5HV - Đen bóng'),
                'alt_text' => 'Camry 2.5HV - Đen bóng',
                'title' => 'Camry 2.5HV - Màu Đen bóng',
                'description' => 'Ảnh màu Đen bóng của Camry 2.5HV',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // GLC 200 colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'GLC 200')->first()->id)->where('color_name', 'Trắng Polar')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Trắng Polar'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Trắng Polar'),
                'alt_text' => 'GLC 200 - Trắng Polar',
                'title' => 'GLC 200 - Màu Trắng Polar',
                'description' => 'Ảnh màu Trắng Polar của GLC 200',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'GLC 200')->first()->id)->where('color_name', 'Đen Obsidian')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Đen Obsidian'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Đen Obsidian'),
                'alt_text' => 'GLC 200 - Đen Obsidian',
                'title' => 'GLC 200 - Màu Đen Obsidian',
                'description' => 'Ảnh màu Đen Obsidian của GLC 200',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'GLC 200')->first()->id)->where('color_name', 'Xám Selenite')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Xám Selenite'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('GLC 200 - Xám Selenite'),
                'alt_text' => 'GLC 200 - Xám Selenite',
                'title' => 'GLC 200 - Màu Xám Selenite',
                'description' => 'Ảnh màu Xám Selenite của GLC 200',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Corolla Altis 1.8HEV colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Corolla Altis 1.8HEV')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Corolla Altis 1.8HEV')->first()->id)->where('color_name', 'Trắng ngọc trai')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Altis 1.8HEV - Trắng ngọc trai'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Altis 1.8HEV - Trắng ngọc trai'),
                'alt_text' => 'Altis 1.8HEV - Trắng ngọc trai',
                'title' => 'Altis 1.8HEV - Màu Trắng ngọc trai',
                'description' => 'Ảnh màu Trắng ngọc trai của Altis 1.8HEV',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'Corolla Altis 1.8HEV')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'Corolla Altis 1.8HEV')->first()->id)->where('color_name', 'Nâu đồng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Altis 1.8HEV - Nâu đồng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('Altis 1.8HEV - Nâu đồng'),
                'alt_text' => 'Altis 1.8HEV - Nâu đồng',
                'title' => 'Altis 1.8HEV - Màu Nâu đồng',
                'description' => 'Ảnh màu Nâu đồng của Altis 1.8HEV',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 3 Series 330i M Sport colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 330i M Sport')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', '3 Series 330i M Sport')->first()->id)->where('color_name', 'Mineral White')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('330i M - Mineral White'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('330i M - Mineral White'),
                'alt_text' => '330i M - Mineral White',
                'title' => '330i M - Mineral White',
                'description' => 'Ảnh màu Mineral White cho 330i M Sport',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', '3 Series 330i M Sport')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', '3 Series 330i M Sport')->first()->id)->where('color_name', 'Portimao Blue')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('330i M - Portimao Blue'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('330i M - Portimao Blue'),
                'alt_text' => '330i M - Portimao Blue',
                'title' => '330i M - Portimao Blue',
                'description' => 'Ảnh màu Portimao Blue cho 330i M Sport',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // VF 9 Eco colors
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'VF 9 Eco')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'VF 9 Eco')->first()->id)->where('color_name', 'Trắng')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('VF 9 Eco - Trắng'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('VF 9 Eco - Trắng'),
                'alt_text' => 'VF 9 Eco - Trắng',
                'title' => 'VF 9 Eco - Màu Trắng',
                'description' => 'Ảnh màu Trắng của VF 9 Eco',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_color_id' => null,
                'car_variant_id' => $variants->where('name', 'VF 9 Eco')->first()->id,
                'car_variant_color_id' => $variantColors->where('car_variant_id', $variants->where('name', 'VF 9 Eco')->first()->id)->where('color_name', 'Xám')->first()->id,
                'image_path' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('VF 9 Eco - Xám'),
                'image_url' => 'https://placehold.co/800x600/111827/ffffff?text=' . urlencode('VF 9 Eco - Xám'),
                'alt_text' => 'VF 9 Eco - Xám',
                'title' => 'VF 9 Eco - Màu Xám',
                'description' => 'Ảnh màu Xám của VF 9 Eco',
                'image_type' => 'gallery',
                'angle' => 'color',
                'width' => 800,
                'height' => 600,
                'file_size' => 0,
                'file_format' => 'jpg',
                'is_main' => false,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('car_variant_images')->truncate();
        CarVariantImage::insert(array_merge($images, $colorImages));
    }
}
