<?php

namespace Database\Seeders;

use App\Models\CarVariantOption;
use App\Models\CarVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarVariantOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Resolve variant IDs once (no foreach seeding logic)
        $variantIdByName = [
            'Vios G' => CarVariant::where('name', 'Vios G')->value('id'),
            'Vios E' => CarVariant::where('name', 'Vios E')->value('id'),
            'City G' => CarVariant::where('name', 'City G')->value('id'),
            'City RS' => CarVariant::where('name', 'City RS')->value('id'),
            'Innova G' => CarVariant::where('name', 'Innova G')->value('id'),
            'Ranger XLT' => CarVariant::where('name', 'Ranger XLT')->value('id'),
            'Accent G' => CarVariant::where('name', 'Accent G')->value('id'),
            'C-Class C200' => CarVariant::where('name', 'C-Class C200')->value('id'),
            '3 Series 320i' => CarVariant::where('name', '3 Series 320i')->value('id'),
            'VF 8 Plus' => CarVariant::where('name', 'VF 8 Plus')->value('id'),
            'Camry 2.5HV' => CarVariant::where('name', 'Camry 2.5HV')->value('id'),
            'Corolla Altis 1.8HEV' => CarVariant::where('name', 'Corolla Altis 1.8HEV')->value('id'),
            'GLC 200' => CarVariant::where('name', 'GLC 200')->value('id'),
            '3 Series 330i M Sport' => CarVariant::where('name', '3 Series 330i M Sport')->value('id'),
            'VF 9 Eco' => CarVariant::where('name', 'VF 9 Eco')->value('id'),
            'CR-V G' => CarVariant::where('name', 'CR-V G')->value('id'),
        ];

        $now = now();
        $t = fn($days) => $now->copy()->subDays($days)->format('Y-m-d H:i:s');

        $options = [
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'option_name' => 'Gói trang trí ngoại thất',
                'description' => 'Viền chrome, ốp gương, đèn LED viền.',
                'option_code' => 'EXT-CHROME-PACK',
                'option_value' => null,
                'category' => 'exterior',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 5000000,
                'package_price' => 5000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Vios+EXT+Pack',
                'icon_path' => 'https://placehold.co/64x64?text=EXT',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => false,
                'sort_order' => 1,
                'specifications' => '"pieces":3,"material":"ABS+Chrome"',
                'compatibility_notes' => 'Chỉ áp dụng bản G/E.',
                'created_at' => $t(120),
                'updated_at' => $t(60),
            ],
            [
                'car_variant_id' => $variantIdByName['Vios G'],
                'option_name' => 'Gói nội thất cao cấp',
                'description' => 'Bọc ghế da, ốp gỗ, thảm sàn 5D.',
                'option_code' => 'INT-PREM-PACK',
                'option_value' => null,
                'category' => 'interior',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 8000000,
                'package_price' => 8500000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Vios+INT+Pack',
                'icon_path' => 'https://placehold.co/64x64?text=INT',
                'is_active' => true,
                'is_popular' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'specifications' => '"leather":"synthetic","color":"black"',
                'compatibility_notes' => 'Phù hợp mọi phiên bản Vios.',
                'created_at' => $t(118),
                'updated_at' => $t(55),
            ],
            [
                'car_variant_id' => $variantIdByName['City G'],
                'option_name' => 'Gói thể thao',
                'description' => 'Cản trước/sau thể thao, lip hai bên.',
                'option_code' => 'EXT-SPORT-KIT',
                'option_value' => null,
                'category' => 'exterior',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 6000000,
                'package_price' => 6000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=City+Sport',
                'icon_path' => 'https://placehold.co/64x64?text=SP',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => false,
                'sort_order' => 1,
                'specifications' => '"aero":"yes"',
                'compatibility_notes' => 'RS dùng bộ khác.',
                'created_at' => $t(100),
                'updated_at' => $t(40),
            ],
            [
                'car_variant_id' => $variantIdByName['City G'],
                'option_name' => 'Âm thanh cao cấp',
                'description' => 'Loa subwoofer, ampli 4 kênh.',
                'option_code' => 'AUD-PREM',
                'option_value' => null,
                'category' => 'audio',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 4000000,
                'package_price' => 4000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Audio+Upgrade',
                'icon_path' => 'https://placehold.co/64x64?text=AUD',
                'is_active' => true,
                'is_popular' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'specifications' => '"channels":4',
                'compatibility_notes' => 'Không áp dụng với cấu hình Bose.',
                'created_at' => $t(99),
                'updated_at' => $t(45),
            ],
            [
                'car_variant_id' => $variantIdByName['C-Class C200'],
                'option_name' => 'Nội thất AMG',
                'description' => 'Ghế thể thao, vô-lăng AMG, ốp nhôm.',
                'option_code' => 'AMG-INT',
                'option_value' => null,
                'category' => 'interior',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 25000000,
                'package_price' => 25900000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=AMG+INT',
                'icon_path' => 'https://placehold.co/64x64?text=AMG',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"seat":"sport","trim":"aluminium"',
                'compatibility_notes' => 'Áp dụng C200/C300.',
                'created_at' => $t(140),
                'updated_at' => $t(20),
            ],
            [
                'car_variant_id' => $variantIdByName['3 Series 320i'],
                'option_name' => 'Gói M Sport',
                'description' => 'Cản M, vô-lăng M, mâm 18 inch.',
                'option_code' => 'M-SPORT',
                'option_value' => null,
                'category' => 'exterior',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 35000000,
                'package_price' => 35000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=M+Sport',
                'icon_path' => 'https://placehold.co/64x64?text=M',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"wheels":"18in"',
                'compatibility_notes' => 'Không áp dụng Luxury Line.',
                'created_at' => $t(160),
                'updated_at' => $t(30),
            ],
            [
                'car_variant_id' => $variantIdByName['VF 8 Plus'],
                'option_name' => 'Gói công nghệ cao cấp',
                'description' => 'ADAS nâng cao, HUD, camera 360 AI.',
                'option_code' => 'TECH-PREMIUM',
                'option_value' => null,
                'category' => 'navigation',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 20000000,
                'package_price' => 21900000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=VF8+Tech',
                'icon_path' => 'https://placehold.co/64x64?text=AI',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"adas":"L2+","hud":"AR"',
                'compatibility_notes' => 'Không áp dụng Eco.',
                'created_at' => $t(90),
                'updated_at' => $t(10),
            ],
            // Camry 2.5HV
            [
                'car_variant_id' => $variantIdByName['Camry 2.5HV'],
                'option_name' => 'Gói an toàn nâng cao',
                'description' => 'Bổ sung cảnh báo điểm mù, cảnh báo phương tiện cắt ngang.',
                'option_code' => 'SAF-PLUS',
                'option_value' => null,
                'category' => 'safety',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 18000000,
                'package_price' => 18900000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Camry+Safety+',
                'icon_path' => 'https://placehold.co/64x64?text=SAFE',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"bsw":true,"rcta":true',
                'compatibility_notes' => 'Áp dụng mọi cấu hình HV.',
                'created_at' => $t(80),
                'updated_at' => $t(20),
            ],
            [
                'car_variant_id' => $variantIdByName['Camry 2.5HV'],
                'option_name' => 'Cửa sổ trời panorama',
                'description' => 'Panorama với rèm che điện.',
                'option_code' => 'ROOF-PANO',
                'option_value' => null,
                'category' => 'comfort',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 22000000,
                'package_price' => 22000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Pano+Roof',
                'icon_path' => 'https://placehold.co/64x64?text=ROOF',
                'is_active' => true,
                'is_popular' => false,
                'is_recommended' => true,
                'sort_order' => 2,
                'specifications' => null,
                'compatibility_notes' => 'Không dùng chung giá đỡ nóc.',
                'created_at' => $t(78),
                'updated_at' => $t(18),
            ],

            // Corolla Altis 1.8HEV
            [
                'car_variant_id' => $variantIdByName['Corolla Altis 1.8HEV'],
                'option_name' => 'Màn hình HUD',
                'description' => 'Hiển thị thông tin lái trên kính lái.',
                'option_code' => 'HUD-DISP',
                'option_value' => null,
                'category' => 'navigation',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 12000000,
                'package_price' => 12000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=HUD',
                'icon_path' => 'https://placehold.co/64x64?text=HUD',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"brightness":auto',
                'compatibility_notes' => 'Không áp dụng bản thường.',
                'created_at' => $t(70),
                'updated_at' => $t(10),
            ],

            // GLC 200
            [
                'car_variant_id' => $variantIdByName['GLC 200'],
                'option_name' => 'Gói Night Package',
                'description' => 'Trang trí ngoại thất đen bóng, mâm tối màu.',
                'option_code' => 'NIGHT-PACK',
                'option_value' => null,
                'category' => 'appearance',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 36000000,
                'package_price' => 36900000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Night+Pack',
                'icon_path' => 'https://placehold.co/64x64?text=N',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => false,
                'sort_order' => 1,
                'specifications' => '"blackout":true',
                'compatibility_notes' => 'Không đi kèm Chrome pack.',
                'created_at' => $t(130),
                'updated_at' => $t(25),
            ],

            // 3 Series 330i M Sport
            [
                'car_variant_id' => $variantIdByName['3 Series 330i M Sport'],
                'option_name' => 'Phanh M Sport',
                'description' => 'Cụm phanh M hiệu suất cao, kẹp màu xanh.',
                'option_code' => 'M-BRAKE',
                'option_value' => null,
                'category' => 'performance',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 42000000,
                'package_price' => 42000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=M+Brake',
                'icon_path' => 'https://placehold.co/64x64?text=MB',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"disc":"ventilated"',
                'compatibility_notes' => 'Chỉ cho mâm 18 inch trở lên.',
                'created_at' => $t(150),
                'updated_at' => $t(35),
            ],

            // VF 9 Eco
            [
                'car_variant_id' => $variantIdByName['VF 9 Eco'],
                'option_name' => 'Gói pin dung lượng lớn',
                'description' => 'Tăng dung lượng pin, phạm vi di chuyển xa hơn.',
                'option_code' => 'BAT-LONG',
                'option_value' => null,
                'category' => 'performance',
                'availability' => 'optional',
                'type' => 'package',
                'price' => 65000000,
                'package_price' => 65000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Long+Range',
                'icon_path' => 'https://placehold.co/64x64?text=BAT',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => '"range_km":+80',
                'compatibility_notes' => 'Không kèm sạc nhanh DC tiêu chuẩn.',
                'created_at' => $t(65),
                'updated_at' => $t(12),
            ],

            // CR-V G
            [
                'car_variant_id' => $variantIdByName['CR-V G'],
                'option_name' => 'Cốp điện rảnh tay',
                'description' => 'Đá cốp tự động, cảm biến chống kẹt.',
                'option_code' => 'TAILGATE-HS',
                'option_value' => null,
                'category' => 'comfort',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 9000000,
                'package_price' => 9000000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Handsfree+Tailgate',
                'icon_path' => 'https://placehold.co/64x64?text=TG',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => null,
                'compatibility_notes' => 'Không dùng chung cản sau thể thao.',
                'created_at' => $t(85),
                'updated_at' => $t(22),
            ],

            // Vios E (bổ sung)
            [
                'car_variant_id' => $variantIdByName['Vios E'],
                'option_name' => 'Camera lùi tích hợp vạch đánh lái',
                'description' => 'Camera góc rộng, hiển thị vạch đánh lái.',
                'option_code' => 'CAM-REV',
                'option_value' => null,
                'category' => 'safety',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 3500000,
                'package_price' => 3500000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Rear+Cam',
                'icon_path' => 'https://placehold.co/64x64?text=CAM',
                'is_active' => true,
                'is_popular' => false,
                'is_recommended' => true,
                'sort_order' => 1,
                'specifications' => null,
                'compatibility_notes' => 'Không áp dụng nếu đã có 360.',
                'created_at' => $t(110),
                'updated_at' => $t(28),
            ],

            // City RS (bổ sung)
            [
                'car_variant_id' => $variantIdByName['City RS'],
                'option_name' => 'Ống xả đôi thể thao',
                'description' => 'Ống xả thể thao, âm thanh trầm.',
                'option_code' => 'EXH-SP',
                'option_value' => null,
                'category' => 'performance',
                'availability' => 'optional',
                'type' => 'standalone',
                'price' => 7500000,
                'package_price' => 7500000,
                'is_included' => false,
                'image_path' => 'https://placehold.co/800x600?text=Sport+Exhaust',
                'icon_path' => 'https://placehold.co/64x64?text=EXH',
                'is_active' => true,
                'is_popular' => true,
                'is_recommended' => false,
                'sort_order' => 2,
                'specifications' => '"sound":"deep"',
                'compatibility_notes' => 'Đạt tiêu chuẩn khí thải VN.',
                'created_at' => $t(95),
                'updated_at' => $t(24),
            ],
        ];

        DB::table('car_variant_options')->truncate();
        CarVariantOption::insert($options);
    }
}
