<?php

namespace Database\Seeders;

use App\Models\CarVariant;
use App\Models\CarModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = CarModel::all();
        $now = now();

        $carVariants = [
            // Toyota Vios Variants
            [
                'car_model_id' => $models->where('name', 'Vios')->first()->id,
                'name' => 'Vios G',
                'slug' => 'toyota-vios-g',
                'sku' => 'VIOS-G-2024',
                'description' => 'Phiên bản cơ bản với đầy đủ tính năng an toàn',
                'short_description' => 'Sedan hạng B cơ bản, tiết kiệm nhiên liệu',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '1.5L',
                'power' => 107,
                'torque' => 140,
                'fuel_consumption' => 5.8,
                'warranty_years' => 3,
                'price' => 520000000,
                'original_price' => 550000000,
                'has_discount' => true,
                'discount_percentage' => 5.45,
                'stock_quantity' => 15,
                    'is_active' => true,
                'is_featured' => false,
                    'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 1250,
                'average_rating' => 4.2,
                'rating_count' => 89,
                'meta_title' => 'Toyota Vios G 2024 - Giá từ 520 triệu',
                'meta_description' => 'Toyota Vios G 2024 - Sedan hạng B cơ bản với giá từ 520 triệu VNĐ',
                'keywords' => 'toyota vios g, giá vios g, vios 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_model_id' => $models->where('name', 'Vios')->first()->id,
                'name' => 'Vios E',
                'slug' => 'toyota-vios-e',
                'sku' => 'VIOS-E-2024',
                'description' => 'Phiên bản nâng cao với nhiều tính năng tiện ích',
                'short_description' => 'Sedan hạng B nâng cao, nhiều tiện ích',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '1.5L',
                'power' => 107,
                'torque' => 140,
                'fuel_consumption' => 5.8,
                'warranty_years' => 3,
                'price' => 580000000,
                'original_price' => 610000000,
                'has_discount' => true,
                'discount_percentage' => 4.92,
                'stock_quantity' => 12,
                'is_active' => true,
                    'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => true,
                'view_count' => 1580,
                'average_rating' => 4.4,
                'rating_count' => 112,
                'meta_title' => 'Toyota Vios E 2024 - Giá từ 580 triệu',
                'meta_description' => 'Toyota Vios E 2024 - Sedan hạng B nâng cao với giá từ 580 triệu VNĐ',
                'keywords' => 'toyota vios e, giá vios e, vios 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_model_id' => $models->where('name', 'Vios')->first()->id,
                'name' => 'Vios G CVT',
                'slug' => 'toyota-vios-g-cvt',
                'sku' => 'VIOS-G-CVT-2024',
                'description' => 'Phiên bản cao cấp với hộp số CVT tiết kiệm nhiên liệu',
                'short_description' => 'Sedan hạng B cao cấp, hộp số CVT',
                'fuel_type' => 'Xăng',
                'transmission' => 'CVT',
                'engine_size' => '1.5L',
                'power' => 107,
                'torque' => 140,
                'fuel_consumption' => 5.5,
                'warranty_years' => 3,
                'price' => 620000000,
                'original_price' => 650000000,
                'has_discount' => true,
                'discount_percentage' => 4.62,
                'stock_quantity' => 8,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => true,
                    'is_bestseller' => false,
                'view_count' => 890,
                'average_rating' => 4.6,
                'rating_count' => 45,
                'meta_title' => 'Toyota Vios G CVT 2024 - Giá từ 620 triệu',
                'meta_description' => 'Toyota Vios G CVT 2024 - Sedan hạng B cao cấp với hộp số CVT',
                'keywords' => 'toyota vios g cvt, giá vios g cvt, vios cvt 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda City Variants
            [
                'car_model_id' => $models->where('name', 'City')->first()->id,
                'name' => 'City G',
                'slug' => 'honda-city-g',
                'sku' => 'CITY-G-2024',
                'description' => 'Phiên bản cơ bản với thiết kế thể thao',
                'short_description' => 'Sedan hạng B cơ bản, thiết kế thể thao',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                    'engine_size' => '1.5L',
                'power' => 119,
                'torque' => 145,
                'fuel_consumption' => 6.0,
                    'warranty_years' => 3,
                'price' => 540000000,
                'original_price' => 570000000,
                'has_discount' => true,
                'discount_percentage' => 5.26,
                'stock_quantity' => 10,
                'is_active' => true,
                    'is_featured' => false,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => true,
                'view_count' => 1100,
                'average_rating' => 4.3,
                'rating_count' => 78,
                'meta_title' => 'Honda City G 2024 - Giá từ 540 triệu',
                'meta_description' => 'Honda City G 2024 - Sedan hạng B cơ bản với giá từ 540 triệu VNĐ',
                'keywords' => 'honda city g, giá city g, city 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_model_id' => $models->where('name', 'City')->first()->id,
                'name' => 'City RS',
                'slug' => 'honda-city-rs',
                'sku' => 'CITY-RS-2024',
                'description' => 'Phiên bản thể thao với thiết kế RS độc đáo',
                'short_description' => 'Sedan hạng B thể thao, thiết kế RS',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                    'engine_size' => '1.5L',
                'power' => 119,
                'torque' => 145,
                'fuel_consumption' => 6.0,
                    'warranty_years' => 3,
                'price' => 620000000,
                'original_price' => 650000000,
                'has_discount' => true,
                'discount_percentage' => 4.62,
                'stock_quantity' => 6,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => false,
                'view_count' => 750,
                'average_rating' => 4.5,
                'rating_count' => 56,
                'meta_title' => 'Honda City RS 2024 - Giá từ 620 triệu',
                'meta_description' => 'Honda City RS 2024 - Sedan hạng B thể thao với thiết kế RS',
                'keywords' => 'honda city rs, giá city rs, city rs 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Innova Variants
            [
                'car_model_id' => $models->where('name', 'Innova')->first()->id,
                'name' => 'Innova G',
                'slug' => 'toyota-innova-g',
                'sku' => 'INNOVA-G-2024',
                'description' => 'MPV đa dụng với không gian rộng rãi',
                'short_description' => 'MPV đa dụng, không gian rộng rãi',
                'fuel_type' => 'Diesel',
                'transmission' => 'Số tự động',
                'engine_size' => '2.4L',
                'power' => 150,
                'torque' => 343,
                'fuel_consumption' => 6.5,
                    'warranty_years' => 3,
                'price' => 950000000,
                'original_price' => 1000000000,
                'has_discount' => true,
                'discount_percentage' => 5.0,
                'stock_quantity' => 8,
                'is_active' => true,
                    'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => true,
                'view_count' => 980,
                'average_rating' => 4.4,
                'rating_count' => 67,
                'meta_title' => 'Toyota Innova G 2024 - Giá từ 950 triệu',
                'meta_description' => 'Toyota Innova G 2024 - MPV đa dụng với giá từ 950 triệu VNĐ',
                'keywords' => 'toyota innova g, giá innova g, innova 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Fortuner Variants
            [
                'car_model_id' => $models->where('name', 'Fortuner')->first()->id,
                'name' => 'Fortuner G',
                'slug' => 'toyota-fortuner-g',
                'sku' => 'FORTUNER-G-2024',
                'description' => 'SUV 7 chỗ cao cấp với khả năng off-road tốt',
                'short_description' => 'SUV 7 chỗ cao cấp, khả năng off-road',
                'fuel_type' => 'Diesel',
                'transmission' => 'Số tự động',
                'engine_size' => '2.8L',
                'power' => 204,
                'torque' => 500,
                'fuel_consumption' => 7.2,
                    'warranty_years' => 3,
                'price' => 1450000000,
                'original_price' => 1500000000,
                'has_discount' => true,
                'discount_percentage' => 3.33,
                'stock_quantity' => 5,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => true,
                'view_count' => 1200,
                'average_rating' => 4.6,
                'rating_count' => 89,
                'meta_title' => 'Toyota Fortuner G 2024 - Giá từ 1.45 tỷ',
                'meta_description' => 'Toyota Fortuner G 2024 - SUV 7 chỗ cao cấp với giá từ 1.45 tỷ VNĐ',
                'keywords' => 'toyota fortuner g, giá fortuner g, fortuner 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda CR-V Variants
            [
                'car_model_id' => $models->where('name', 'CR-V')->first()->id,
                'name' => 'CR-V G',
                'slug' => 'honda-cr-v-g',
                'sku' => 'CRV-G-2024',
                'description' => 'SUV 5 chỗ với thiết kế hiện đại và công nghệ tiên tiến',
                'short_description' => 'SUV 5 chỗ hiện đại, công nghệ tiên tiến',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '1.5L',
                'power' => 188,
                'torque' => 243,
                'fuel_consumption' => 6.8,
                    'warranty_years' => 3,
                'price' => 1250000000,
                'original_price' => 1300000000,
                'has_discount' => true,
                'discount_percentage' => 3.85,
                'stock_quantity' => 6,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => false,
                'view_count' => 850,
                'average_rating' => 4.5,
                'rating_count' => 72,
                'meta_title' => 'Honda CR-V G 2024 - Giá từ 1.25 tỷ',
                'meta_description' => 'Honda CR-V G 2024 - SUV 5 chỗ hiện đại với giá từ 1.25 tỷ VNĐ',
                'keywords' => 'honda cr-v g, giá cr-v g, cr-v 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Ford Ranger Variants
            [
                'car_model_id' => $models->where('name', 'Ranger')->first()->id,
                    'name' => 'Ranger XLT',
                'slug' => 'ford-ranger-xlt',
                'sku' => 'RANGER-XLT-2024',
                'description' => 'Pickup truck mạnh mẽ với khả năng tải trọng cao',
                'short_description' => 'Pickup truck mạnh mẽ, tải trọng cao',
                'fuel_type' => 'Diesel',
                'transmission' => 'Số tự động',
                'engine_size' => '2.0L',
                'power' => 170,
                'torque' => 420,
                'fuel_consumption' => 7.5,
                    'warranty_years' => 3,
                'price' => 980000000,
                'original_price' => 1020000000,
                'has_discount' => true,
                'discount_percentage' => 3.92,
                'stock_quantity' => 4,
                'is_active' => true,
                    'is_featured' => false,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => true,
                'view_count' => 650,
                'average_rating' => 4.3,
                'rating_count' => 45,
                'meta_title' => 'Ford Ranger XLT 2024 - Giá từ 980 triệu',
                'meta_description' => 'Ford Ranger XLT 2024 - Pickup truck mạnh mẽ với giá từ 980 triệu VNĐ',
                'keywords' => 'ford ranger xlt, giá ranger xlt, ranger 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Hyundai Accent Variants
            [
                'car_model_id' => $models->where('name', 'Accent')->first()->id,
                'name' => 'Accent G',
                'slug' => 'hyundai-accent-g',
                'sku' => 'ACCENT-G-2024',
                'description' => 'Sedan hạng B với thiết kế hiện đại và giá cả cạnh tranh',
                'short_description' => 'Sedan hạng B hiện đại, giá cạnh tranh',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '1.4L',
                'power' => 100,
                'torque' => 133,
                'fuel_consumption' => 5.8,
                'warranty_years' => 5,
                'price' => 480000000,
                'original_price' => 510000000,
                'has_discount' => true,
                'discount_percentage' => 5.88,
                'stock_quantity' => 12,
                'is_active' => true,
                'is_featured' => false,
                'is_available' => true,
                    'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 920,
                'average_rating' => 4.1,
                'rating_count' => 58,
                'meta_title' => 'Hyundai Accent G 2024 - Giá từ 480 triệu',
                'meta_description' => 'Hyundai Accent G 2024 - Sedan hạng B hiện đại với giá từ 480 triệu VNĐ',
                'keywords' => 'hyundai accent g, giá accent g, accent 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mercedes-Benz C-Class Variants
            [
                'car_model_id' => $models->where('name', 'C-Class')->first()->id,
                'name' => 'C-Class C200',
                'slug' => 'mercedes-benz-c-class-c200',
                'sku' => 'C-CLASS-C200-2024',
                'description' => 'Sedan hạng D cao cấp với sự sang trọng và công nghệ tiên tiến',
                'short_description' => 'Sedan hạng D cao cấp, sang trọng',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                    'engine_size' => '2.0L',
                'power' => 204,
                'torque' => 300,
                'fuel_consumption' => 7.2,
                    'warranty_years' => 3,
                'price' => 2200000000,
                'original_price' => 2300000000,
                'has_discount' => true,
                'discount_percentage' => 4.35,
                'stock_quantity' => 3,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => false,
                'view_count' => 450,
                'average_rating' => 4.8,
                'rating_count' => 23,
                'meta_title' => 'Mercedes-Benz C-Class C200 2024 - Giá từ 2.2 tỷ',
                'meta_description' => 'Mercedes-Benz C-Class C200 2024 - Sedan hạng D cao cấp với giá từ 2.2 tỷ VNĐ',
                'keywords' => 'mercedes-benz c-class c200, giá c-class c200, c-class 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Mercedes-Benz GLC Variants
            [
                'car_model_id' => $models->where('name', 'GLC')->first()->id,
                'name' => 'GLC 200',
                'slug' => 'mercedes-benz-glc-200',
                'sku' => 'GLC-200-2024',
                'description' => 'SUV hạng sang 5 chỗ, thiết kế sang trọng',
                'short_description' => 'GLC 200 RWD, tiện nghi đầy đủ',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '2.0L',
                'power' => 197,
                'torque' => 320,
                'fuel_consumption' => 7.9,
                'warranty_years' => 3,
                'price' => 2199000000,
                'original_price' => 2199000000,
                'has_discount' => false,
                'discount_percentage' => 0,
                'stock_quantity' => 3,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 520,
                'average_rating' => 4.7,
                'rating_count' => 38,
                'meta_title' => 'Mercedes-Benz GLC 200 2024',
                'meta_description' => 'SUV hạng sang 5 chỗ, tiện nghi sang trọng',
                'keywords' => 'glc 200',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BMW 3 Series Variants
            [
                'car_model_id' => $models->where('name', '3 Series')->first()->id,
                'name' => '3 Series 320i',
                'slug' => 'bmw-3-series-320i',
                'sku' => '3-SERIES-320I-2024',
                'description' => 'Sedan hạng D thể thao với hiệu suất cao',
                'short_description' => 'Sedan hạng D thể thao, hiệu suất cao',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                    'engine_size' => '2.0L',
                'power' => 170,
                'torque' => 250,
                'fuel_consumption' => 6.8,
                    'warranty_years' => 3,
                'price' => 2100000000,
                'original_price' => 2200000000,
                'has_discount' => true,
                'discount_percentage' => 4.55,
                'stock_quantity' => 2,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                    'is_new_arrival' => false,
                    'is_bestseller' => false,
                'view_count' => 380,
                'average_rating' => 4.7,
                'rating_count' => 18,
                'meta_title' => 'BMW 3 Series 320i 2024 - Giá từ 2.1 tỷ',
                'meta_description' => 'BMW 3 Series 320i 2024 - Sedan hạng D thể thao với giá từ 2.1 tỷ VNĐ',
                'keywords' => 'bmw 3 series 320i, giá 3 series 320i, 3 series 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_model_id' => $models->where('name', '3 Series')->first()->id,
                'name' => '3 Series 330i M Sport',
                'slug' => 'bmw-3-series-330i-m-sport',
                'sku' => '3-SERIES-330I-MSPORT-2024',
                'description' => 'Sedan hạng D hiệu suất cao gói M Sport',
                'short_description' => '330i, treo M Sport, hiệu suất mạnh mẽ',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '2.0L',
                'power' => 258,
                'torque' => 400,
                'fuel_consumption' => 6.5,
                'warranty_years' => 3,
                'price' => 2299000000,
                'original_price' => 2399000000,
                'has_discount' => true,
                'discount_percentage' => 4.17,
                'stock_quantity' => 2,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 410,
                'average_rating' => 4.8,
                'rating_count' => 21,
                'meta_title' => 'BMW 3 Series 330i M Sport 2024',
                'meta_description' => 'Sedan hạng D, gói M Sport hiệu suất cao',
                'keywords' => '330i m sport',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // VinFast VF 8 Variants
            [
                'car_model_id' => $models->where('name', 'VF 8')->first()->id,
                'name' => 'VF 8 Plus',
                'slug' => 'vinfast-vf-8-plus',
                'sku' => 'VF8-PLUS-2024',
                'description' => 'SUV điện 5 chỗ với công nghệ hiện đại và thiết kế độc đáo',
                'short_description' => 'SUV điện 5 chỗ, công nghệ hiện đại',
                'fuel_type' => 'Điện',
                'transmission' => 'Đơn tốc độ',
                'engine_size' => 'Động cơ điện',
                'power' => 402,
                'torque' => 620,
                'fuel_consumption' => 0,
                'warranty_years' => 7,
                'price' => 1200000000,
                'original_price' => 1250000000,
                'has_discount' => true,
                'discount_percentage' => 4.0,
                'stock_quantity' => 8,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => true,
                'is_bestseller' => true,
                'view_count' => 1500,
                'average_rating' => 4.4,
                'rating_count' => 95,
                'meta_title' => 'VinFast VF 8 Plus 2024 - Giá từ 1.2 tỷ',
                'meta_description' => 'VinFast VF 8 Plus 2024 - SUV điện 5 chỗ với giá từ 1.2 tỷ VNĐ',
                'keywords' => 'vinfast vf 8 plus, giá vf 8 plus, vf 8 2024',
                'created_at' => $now,
                'updated_at' => $now,
            ]
            ,
            // Add variants for newly added models
            // Toyota Corolla Cross
            [
                'car_model_id' => $models->where('name', 'Corolla Cross')->first()->id,
                'name' => 'Corolla Cross G',
                'slug' => 'toyota-corolla-cross-g',
                'sku' => 'CCROSS-G-2024',
                'description' => 'Bản tiêu chuẩn, an toàn đầy đủ',
                'short_description' => 'Crossover đô thị an toàn',
                'fuel_type' => 'Xăng',
                'transmission' => 'CVT',
                'engine_size' => '1.8L',
                'power' => 138,
                'torque' => 172,
                'fuel_consumption' => 6.5,
                'warranty_years' => 3,
                'price' => 720000000,
                'original_price' => 750000000,
                'has_discount' => true,
                'discount_percentage' => 4.0,
                'stock_quantity' => 10,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 980,
                'average_rating' => 4.4,
                'rating_count' => 66,
                'meta_title' => 'Toyota Corolla Cross G 2024',
                'meta_description' => 'Crossover đô thị an toàn, tiết kiệm',
                'keywords' => 'corolla cross g',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // VinFast VF 9 Variants
            [
                'car_model_id' => $models->where('name', 'VF 9')->first()->id,
                'name' => 'VF 9 Eco',
                'slug' => 'vinfast-vf-9-eco',
                'sku' => 'VF9-ECO-2024',
                'description' => 'SUV điện 7 chỗ cao cấp, quãng đường xa',
                'short_description' => 'VF 9 Eco pin lớn, công nghệ an toàn',
                'fuel_type' => 'Điện',
                'transmission' => 'Đơn tốc độ',
                'engine_size' => 'Động cơ điện',
                'power' => 402,
                'torque' => 620,
                'fuel_consumption' => 0,
                'warranty_years' => 10,
                'price' => 1490000000,
                'original_price' => 1550000000,
                'has_discount' => true,
                'discount_percentage' => 3.87,
                'stock_quantity' => 5,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => true,
                'is_bestseller' => true,
                'view_count' => 630,
                'average_rating' => 4.2,
                'rating_count' => 33,
                'meta_title' => 'VinFast VF 9 Eco 2024',
                'meta_description' => 'SUV điện 7 chỗ, pin lớn, an toàn',
                'keywords' => 'vf 9 eco',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Toyota Corolla Altis
            [
                'car_model_id' => $models->where('name', 'Corolla Altis')->first()->id,
                'name' => 'Corolla Altis 1.8HEV',
                'slug' => 'toyota-corolla-altis-18hev',
                'sku' => 'COROLLA-ALTIS-18HEV-2024',
                'description' => 'Sedan hạng C hybrid tiết kiệm nhiên liệu',
                'short_description' => 'Hybrid 1.8L e-CVT, an toàn Toyota Safety Sense',
                'fuel_type' => 'Hybrid',
                'transmission' => 'e-CVT',
                'engine_size' => '1.8L',
                'power' => 122,
                'torque' => 142,
                'fuel_consumption' => 4.5,
                'warranty_years' => 3,
                'price' => 860000000,
                'original_price' => 895000000,
                'has_discount' => true,
                'discount_percentage' => 3.91,
                'stock_quantity' => 7,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 740,
                'average_rating' => 4.5,
                'rating_count' => 64,
                'meta_title' => 'Toyota Corolla Altis 1.8HEV 2024',
                'meta_description' => 'Sedan hạng C Hybrid tiết kiệm, an toàn TSS',
                'keywords' => 'corolla altis hybrid 1.8',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Toyota Camry
            [
                'car_model_id' => $models->where('name', 'Camry')->first()->id,
                'name' => 'Camry 2.5HV',
                'slug' => 'toyota-camry-25hv',
                'sku' => 'CAMRY-25HV-2024',
                'description' => 'Sedan hạng D hybrid cao cấp, êm ái',
                'short_description' => '2.5L Hybrid e-CVT, nhiều công nghệ an toàn',
                'fuel_type' => 'Hybrid',
                'transmission' => 'e-CVT',
                'engine_size' => '2.5L',
                'power' => 211,
                'torque' => 221,
                'fuel_consumption' => 5.0,
                'warranty_years' => 3,
                'price' => 1450000000,
                'original_price' => 1490000000,
                'has_discount' => true,
                'discount_percentage' => 2.68,
                'stock_quantity' => 4,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 680,
                'average_rating' => 4.7,
                'rating_count' => 52,
                'meta_title' => 'Toyota Camry 2.5HV 2024',
                'meta_description' => 'Sedan hạng D Hybrid sang trọng, êm ái',
                'keywords' => 'camry 2.5hv hybrid',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Hyundai Creta
            [
                'car_model_id' => $models->where('name', 'Creta')->first()->id,
                'name' => 'Creta Premium',
                'slug' => 'hyundai-creta-premium',
                'sku' => 'CRETA-PREM-2024',
                'description' => 'Bản cao cấp, nhiều công nghệ',
                'short_description' => 'SUV đô thị cao cấp',
                'fuel_type' => 'Xăng',
                'transmission' => 'CVT',
                'engine_size' => '1.5L',
                'power' => 113,
                'torque' => 144,
                'fuel_consumption' => 6.2,
                'warranty_years' => 5,
                'price' => 680000000,
                'original_price' => 700000000,
                'has_discount' => true,
                'discount_percentage' => 2.9,
                'stock_quantity' => 12,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 840,
                'average_rating' => 4.3,
                'rating_count' => 54,
                'meta_title' => 'Hyundai Creta Premium 2024',
                'meta_description' => 'SUV đô thị, công nghệ an toàn',
                'keywords' => 'creta premium',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Kia Carnival
            [
                'car_model_id' => $models->where('name', 'Carnival')->first()->id,
                'name' => 'Carnival Signature 7',
                'slug' => 'kia-carnival-signature-7',
                'sku' => 'CARNIVAL-S7-2024',
                'description' => 'MPV 7 chỗ cao cấp, tiện nghi',
                'short_description' => 'MPV cao cấp',
                'fuel_type' => 'Diesel',
                'transmission' => 'Số tự động',
                'engine_size' => '2.2L',
                'power' => 198,
                'torque' => 440,
                'fuel_consumption' => 7.8,
                'warranty_years' => 3,
                'price' => 1420000000,
                'original_price' => 1480000000,
                'has_discount' => true,
                'discount_percentage' => 4.1,
                'stock_quantity' => 6,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => true,
                'view_count' => 760,
                'average_rating' => 4.6,
                'rating_count' => 31,
                'meta_title' => 'Kia Carnival Signature 7 2024',
                'meta_description' => 'MPV 7 chỗ tiện nghi cao cấp',
                'keywords' => 'carnival signature 7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Mazda CX-5
            [
                'car_model_id' => $models->where('name', 'CX-5')->first()->id,
                'name' => 'CX-5 2.0 Premium',
                'slug' => 'mazda-cx-5-20-premium',
                'sku' => 'CX5-20-PREM-2024',
                'description' => 'SUV 5 chỗ, gói an toàn i-Activsense',
                'short_description' => 'SUV 5 chỗ cao cấp',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '2.0L',
                'power' => 154,
                'torque' => 200,
                'fuel_consumption' => 6.9,
                'warranty_years' => 3,
                'price' => 870000000,
                'original_price' => 910000000,
                'has_discount' => true,
                'discount_percentage' => 4.4,
                'stock_quantity' => 9,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 690,
                'average_rating' => 4.5,
                'rating_count' => 40,
                'meta_title' => 'Mazda CX-5 2.0 Premium 2024',
                'meta_description' => 'SUV 5 chỗ an toàn i-Activsense',
                'keywords' => 'cx-5 premium',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // BMW X5
            [
                'car_model_id' => $models->where('name', 'X5')->first()->id,
                'name' => 'X5 xDrive40i',
                'slug' => 'bmw-x5-xdrive40i',
                'sku' => 'X5-40I-2024',
                'description' => 'SUV hạng sang hiệu suất cao',
                'short_description' => 'SUV hạng sang',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '3.0L',
                'power' => 335,
                'torque' => 450,
                'fuel_consumption' => 8.5,
                'warranty_years' => 3,
                'price' => 4200000000,
                'original_price' => 4350000000,
                'has_discount' => true,
                'discount_percentage' => 3.4,
                'stock_quantity' => 2,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 320,
                'average_rating' => 4.8,
                'rating_count' => 12,
                'meta_title' => 'BMW X5 xDrive40i 2024',
                'meta_description' => 'SUV hạng sang hiệu suất cao',
                'keywords' => 'bmw x5 xdrive40i',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Audi Q5
            [
                'car_model_id' => $models->where('name', 'Q5')->first()->id,
                'name' => 'Q5 45 TFSI quattro',
                'slug' => 'audi-q5-45-tfsi-quattro',
                'sku' => 'Q5-45TFSI-2024',
                'description' => 'SUV hạng sang, dẫn động Quattro',
                'short_description' => 'SUV hạng sang 5 chỗ',
                'fuel_type' => 'Xăng',
                'transmission' => 'Số tự động',
                'engine_size' => '2.0L',
                'power' => 261,
                'torque' => 370,
                'fuel_consumption' => 7.4,
                'warranty_years' => 3,
                'price' => 2500000000,
                'original_price' => 2600000000,
                'has_discount' => true,
                'discount_percentage' => 3.8,
                'stock_quantity' => 3,
                'is_active' => true,
                'is_featured' => true,
                'is_available' => true,
                'is_new_arrival' => false,
                'is_bestseller' => false,
                'view_count' => 410,
                'average_rating' => 4.7,
                'rating_count' => 18,
                'meta_title' => 'Audi Q5 45 TFSI quattro 2024',
                'meta_description' => 'SUV hạng sang dẫn động Quattro',
                'keywords' => 'audi q5 45 tfsi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        DB::table('car_variants')->truncate();
        CarVariant::insert($carVariants);
    }
}
