<?php

namespace Database\Seeders;

use App\Models\CarVariantFeature;
use App\Models\CarVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarVariantFeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $variants = CarVariant::all();
        $now = now();

        $features = [
            // Toyota Vios G Features
            [
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS giúp tăng độ an toàn khi phanh gấp',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Túi khí đôi',
                'description' => 'Hệ thống túi khí đôi bảo vệ người lái và hành khách phía trước',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'AIRBAG_FRONT',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Vios G')->first()->id,
                'category' => 'comfort',
                'feature_name' => 'Điều hòa tự động',
                'description' => 'Hệ thống điều hòa tự động với điều khiển nhiệt độ chính xác',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'AUTO_AC',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Vios E Features
            [
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS tiêu chuẩn',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Vios E')->first()->id,
                'category' => 'comfort',
                'feature_name' => 'Điều hòa thủ công',
                'description' => 'Hệ thống điều hòa thủ công cơ bản',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'MANUAL_AC',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda City G Features
            [
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS với phân phối lực phanh điện tử',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'City G')->first()->id,
                'category' => 'technology',
                'feature_name' => 'Màn hình cảm ứng 8 inch',
                'description' => 'Màn hình cảm ứng 8 inch với Apple CarPlay và Android Auto',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'TOUCH_8IN',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Honda City RS Features
            [
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS nâng cao',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'City RS')->first()->id,
                'category' => 'performance',
                'feature_name' => 'Chế độ thể thao',
                'description' => 'Chế độ lái thể thao với phản ứng động cơ nhanh hơn',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'SPORT_MODE',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Toyota Innova G Features
            [
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS cho xe đa dụng',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Innova G')->first()->id,
                'category' => 'comfort',
                'feature_name' => 'Ghế 7 chỗ',
                'description' => 'Ghế 7 chỗ với không gian rộng rãi cho gia đình',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'SEAT_7',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Ford Ranger XLT Features
            [
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS cho xe tải',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Ranger XLT')->first()->id,
                'category' => 'performance',
                'feature_name' => 'Động cơ 2.0L Turbo',
                'description' => 'Động cơ 2.0L Turbo mạnh mẽ với khả năng tải trọng cao',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ENG_20T',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Hyundai Accent G Features
            [
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS cơ bản',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Accent G')->first()->id,
                'category' => 'comfort',
                'feature_name' => 'Điều hòa thủ công',
                'description' => 'Hệ thống điều hòa thủ công tiết kiệm nhiên liệu',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 0,
                'feature_code' => 'MANUAL_AC',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mercedes-Benz C-Class C200 Features
            [
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS cao cấp với nhiều tính năng an toàn',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'C-Class C200')->first()->id,
                'category' => 'interior',
                'feature_name' => 'Nội thất da cao cấp',
                'description' => 'Nội thất da cao cấp với thiết kế sang trọng',
                'availability' => 'standard',
                'importance' => 'luxury',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'LEATHER_INT',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BMW 3 Series 320i Features
            [
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS thể thao với hiệu suất cao',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', '3 Series 320i')->first()->id,
                'category' => 'performance',
                'feature_name' => 'Chế độ lái thể thao',
                'description' => 'Chế độ lái thể thao với phản ứng động cơ và hệ thống treo tối ưu',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'SPORT_MODE',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // VinFast VF 8 Plus Features
            [
                'car_variant_id' => $variants->where('name', 'VF 8 Plus')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Hệ thống phanh ABS',
                'description' => 'Hệ thống chống bó phanh ABS điện tử hiện đại',
                'availability' => 'standard',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'ABS',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'VF 8 Plus')->first()->id,
                'category' => 'technology',
                'feature_name' => 'Động cơ điện',
                'description' => 'Động cơ điện hiện đại với hiệu suất cao và thân thiện môi trường',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'E_MOTOR',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ]
            ,

            // Toyota Camry 2.5HV Features
            [
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Toyota Safety Sense (TSS)',
                'description' => 'Gói an toàn chủ động gồm PCS, LDA, LTA, ACC, AHB',
                'availability' => 'package',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 25000000,
                'feature_code' => 'TSS_PACK',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'category' => 'technology',
                'feature_name' => 'Hiển thị kính lái (HUD)',
                'description' => 'Hiển thị thông tin trên kính lái giúp quan sát an toàn',
                'availability' => 'optional',
                'importance' => 'nice_to_have',
                'price' => 0,
                'package_price' => 15000000,
                'feature_code' => 'HUD',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'Camry 2.5HV')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Camera 360 độ',
                'description' => 'Hỗ trợ quan sát toàn cảnh khi đỗ xe',
                'availability' => 'optional',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 12000000,
                'feature_code' => 'CAM360',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mercedes-Benz GLC 200 Features
            [
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'category' => 'exterior',
                'feature_name' => 'AMG Line Exterior Package',
                'description' => 'Gói ngoại thất AMG Line với cản trước/sau thể thao, mâm AMG',
                'availability' => 'package',
                'importance' => 'luxury',
                'price' => 0,
                'package_price' => 80000000,
                'feature_code' => 'AMG_EXT',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'category' => 'entertainment',
                'feature_name' => 'Âm thanh Burmester 13 loa',
                'description' => 'Hệ thống âm thanh cao cấp Burmester',
                'availability' => 'optional',
                'importance' => 'luxury',
                'price' => 0,
                'package_price' => 30000000,
                'feature_code' => 'BURMESTER',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'GLC 200')->first()->id,
                'category' => 'comfort',
                'feature_name' => 'Cửa sổ trời Panoramic',
                'description' => 'Cửa sổ trời toàn cảnh tăng trải nghiệm ánh sáng',
                'availability' => 'optional',
                'importance' => 'nice_to_have',
                'price' => 0,
                'package_price' => 35000000,
                'feature_code' => 'PANORAMA',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // BMW 3 Series 330i M Sport Features
            [
                'car_variant_id' => $variants->where('name', '3 Series 330i M Sport')->first()->id,
                'category' => 'performance',
                'feature_name' => 'Vi sai M Sport',
                'description' => 'Vi sai thể thao M giúp tăng độ bám và ổn định khi vào cua',
                'availability' => 'optional',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 40000000,
                'feature_code' => 'M_DIFF',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', '3 Series 330i M Sport')->first()->id,
                'category' => 'performance',
                'feature_name' => 'Hệ thống treo Adaptive M',
                'description' => 'Treo Adaptive M điều chỉnh theo chế độ lái',
                'availability' => 'optional',
                'importance' => 'important',
                'price' => 0,
                'package_price' => 25000000,
                'feature_code' => 'M_SUSP',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', '3 Series 330i M Sport')->first()->id,
                'category' => 'technology',
                'feature_name' => 'Live Cockpit Professional',
                'description' => 'Cụm đồng hồ kỹ thuật số + màn hình trung tâm lớn',
                'availability' => 'standard',
                'importance' => 'important',
                'price' => 0,
                'package_price' => null,
                'feature_code' => 'LIVE_COCKPIT_PRO',
                'icon_path' => null,
                'is_included' => true,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // VinFast VF 9 Eco Features
            [
                'car_variant_id' => $variants->where('name', 'VF 9 Eco')->first()->id,
                'category' => 'safety',
                'feature_name' => 'Gói ADAS nâng cao',
                'description' => 'Hỗ trợ lái nâng cao: giữ làn, ga tự động thích ứng, phanh khẩn cấp',
                'availability' => 'package',
                'importance' => 'essential',
                'price' => 0,
                'package_price' => 20000000,
                'feature_code' => 'ADAS_PLUS',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'VF 9 Eco')->first()->id,
                'category' => 'technology',
                'feature_name' => 'Bơm nhiệt (Heat Pump)',
                'description' => 'Tối ưu hiệu suất nhiệt cho hệ thống điều hòa, tăng tầm hoạt động',
                'availability' => 'optional',
                'importance' => 'nice_to_have',
                'price' => 0,
                'package_price' => 10000000,
                'feature_code' => 'HEAT_PUMP',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'car_variant_id' => $variants->where('name', 'VF 9 Eco')->first()->id,
                'category' => 'interior',
                'feature_name' => 'Ghế độc lập hàng 2 (Captain Seats)',
                'description' => 'Ghế độc lập hàng 2 kèm bệ tỳ tay, thoải mái trên hành trình dài',
                'availability' => 'optional',
                'importance' => 'luxury',
                'price' => 0,
                'package_price' => 15000000,
                'feature_code' => 'CAPTAIN_SEATS',
                'icon_path' => null,
                'is_included' => false,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        DB::table('car_variant_features')->truncate();
        CarVariantFeature::insert($features);
    }
}
