<?php

namespace Database\Seeders;

use App\Models\CustomerProfile;
use App\Models\User;
use Illuminate\Database\Seeder;

class CustomerProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::where('role', 'user')->get();

        $profiles = [
            // VIP Customer Profile
            [
                'user_id' => $users->where('email', 'vip@example.com')->first()->id,
                'birth_date' => '1985-03-15',
                'gender' => 'male',
                'nationality' => 'Vietnamese',
                'id_card_number' => '123456789012',
                'emergency_contact_name' => 'Nguyễn Văn B',
                'emergency_contact_phone' => '0901234579',
                'emergency_contact_relationship' => 'Anh trai',
                'occupation' => 'Giám đốc công ty',
                'company_name' => 'Công ty TNHH VIP',
                'job_title' => 'CEO',
                'work_phone' => '0901234580',
                'work_email' => 'ceo@vipcompany.com',
                'monthly_income' => 50000000,
                'income_source' => 'Lương và thưởng',
                'bank_name' => 'Vietcombank',
                'bank_account_number' => '1234567890',
                'credit_score' => 850,
                'has_existing_loan' => false,
                'driver_license_number' => 'B2-123456',
                'driver_license_issue_date' => '2010-01-01',
                'driver_license_expiry_date' => '2030-01-01',
                'driver_license_class' => 'B2',
                'driving_experience_years' => 15,
                'driving_history' => 'Lái xe an toàn, không có vi phạm',
                'preferred_car_types' => ['sedan', 'suv'],
                'preferred_brands' => ['Mercedes-Benz', 'BMW', 'Audi'],
                'preferred_colors' => ['Đen bóng', 'Trắng ngọc trai', 'Xám bạc'],
                'budget_min' => 2000000000,
                'budget_max' => 5000000000,
                'purchase_purpose' => 'Cá nhân và công việc',
                'special_requirements' => 'Khách hàng VIP - ưu tiên cao, cần dịch vụ đặc biệt',
                'marital_status' => 'married',
                'family_size' => 4,
                'has_children' => true,
                'children_count' => 2,
                'family_vehicles' => ['Mercedes-Benz C-Class 2020'],
                'customer_type' => 'vip',
                'lead_source' => 'Giới thiệu',
                'first_contact_date' => '2020-01-01',
                'last_contact_date' => now(),
                'total_visits' => 25,
                'total_test_drives' => 8,
                'sales_notes' => 'Khách hàng VIP với khả năng chi trả cao, thích xe cao cấp',
                'sales_stage' => 'closed',
                'consent_to_marketing' => true,
                'marketing_preferences' => ['email', 'sms', 'call'],
                'consent_to_sms' => true,
                'consent_to_email' => true,
                'consent_to_call' => true,
                'is_active' => true,
                'is_vip' => true,
                'status' => 'active',
                'satisfaction_score' => 5.0,
                'feedback' => 'Dịch vụ xuất sắc, nhân viên chuyên nghiệp',
                'created_at' => now()->subYears(2),
                'updated_at' => now()->subDays(7)
            ],

            // Regular Customer 1 Profile
            [
                'user_id' => $users->where('email', 'customer1@example.com')->first()->id,
                'birth_date' => '1990-07-20',
                'gender' => 'female',
                'nationality' => 'Vietnamese',
                'id_card_number' => '123456789013',
                'emergency_contact_name' => 'Trần Văn C',
                'emergency_contact_phone' => '0901234581',
                'emergency_contact_relationship' => 'Chồng',
                'occupation' => 'Kế toán',
                'company_name' => 'Công ty TNHH ABC',
                'job_title' => 'Kế toán trưởng',
                'work_phone' => '0901234582',
                'work_email' => 'accountant@abc.com',
                'monthly_income' => 15000000,
                'income_source' => 'Lương',
                'bank_name' => 'Techcombank',
                'bank_account_number' => '1234567891',
                'credit_score' => 720,
                'has_existing_loan' => true,
                'existing_loan_details' => 'Vay mua nhà tại Vietcombank',
                'driver_license_number' => 'B2-123457',
                'driver_license_issue_date' => '2015-06-01',
                'driver_license_expiry_date' => '2035-06-01',
                'driver_license_class' => 'B2',
                'driving_experience_years' => 8,
                'driving_history' => 'Lái xe an toàn',
                'preferred_car_types' => ['sedan', 'hatchback'],
                'preferred_brands' => ['Toyota', 'Honda'],
                'preferred_colors' => ['Trắng ngọc trai', 'Đen bóng', 'Bạc kim loại'],
                'budget_min' => 500000000,
                'budget_max' => 1000000000,
                'purchase_purpose' => 'Cá nhân',
                'special_requirements' => 'Cần xe tiết kiệm nhiên liệu, dễ bảo dưỡng',
                'marital_status' => 'married',
                'family_size' => 3,
                'has_children' => true,
                'children_count' => 1,
                'family_vehicles' => ['Toyota Vios 2018'],
                'customer_type' => 'returning',
                'lead_source' => 'Website',
                'first_contact_date' => '2021-03-15',
                'last_contact_date' => now(),
                'total_visits' => 12,
                'total_test_drives' => 3,
                'sales_notes' => 'Khách hàng thường xuyên, ưa chuộng xe Nhật Bản',
                'sales_stage' => 'qualified',
                'consent_to_marketing' => true,
                'marketing_preferences' => ['email', 'sms'],
                'consent_to_sms' => true,
                'consent_to_email' => true,
                'consent_to_call' => false,
                'is_active' => true,
                'is_vip' => false,
                'status' => 'active',
                'satisfaction_score' => 4.5,
                'feedback' => 'Dịch vụ tốt, giá cả hợp lý',
                'created_at' => now()->subYears(2),
                'updated_at' => now()->subDays(10)
            ],

            // Regular Customer 2 Profile
            [
                'user_id' => $users->where('email', 'customer2@example.com')->first()->id,
                'birth_date' => '1988-11-10',
                'gender' => 'male',
                'nationality' => 'Vietnamese',
                'id_card_number' => '123456789014',
                'emergency_contact_name' => 'Lê Thị D',
                'emergency_contact_phone' => '0901234583',
                'emergency_contact_relationship' => 'Vợ',
                'occupation' => 'Kỹ sư',
                'company_name' => 'Công ty TNHH XYZ',
                'job_title' => 'Kỹ sư trưởng',
                'work_phone' => '0901234584',
                'work_email' => 'engineer@xyz.com',
                'monthly_income' => 25000000,
                'income_source' => 'Lương và thưởng',
                'bank_name' => 'BIDV',
                'bank_account_number' => '1234567892',
                'credit_score' => 780,
                'has_existing_loan' => false,
                'driver_license_number' => 'B2-123458',
                'driver_license_issue_date' => '2012-09-01',
                'driver_license_expiry_date' => '2032-09-01',
                'driver_license_class' => 'B2',
                'driving_experience_years' => 12,
                'driving_history' => 'Lái xe an toàn, ít vi phạm',
                'preferred_car_types' => ['suv', 'pickup'],
                'preferred_brands' => ['Ford', 'Hyundai'],
                'preferred_colors' => ['Xám đậm', 'Đen bóng', 'Trắng ngọc trai'],
                'budget_min' => 800000000,
                'budget_max' => 1500000000,
                'purchase_purpose' => 'Công việc và gia đình',
                'special_requirements' => 'Cần xe đa dụng, chở hàng và gia đình',
                'marital_status' => 'married',
                'family_size' => 5,
                'has_children' => true,
                'children_count' => 3,
                'family_vehicles' => ['Ford Ranger 2019'],
                'customer_type' => 'returning',
                'lead_source' => 'Giới thiệu',
                'first_contact_date' => '2022-01-10',
                'last_contact_date' => now(),
                'total_visits' => 8,
                'total_test_drives' => 2,
                'sales_notes' => 'Khách hàng ưa chuộng xe đa dụng',
                'sales_stage' => 'proposal',
                'consent_to_marketing' => true,
                'marketing_preferences' => ['email'],
                'consent_to_sms' => false,
                'consent_to_email' => true,
                'consent_to_call' => false,
                'is_active' => true,
                'is_vip' => false,
                'status' => 'active',
                'satisfaction_score' => 4.0,
                'feedback' => 'Dịch vụ ổn, cần cải thiện thời gian giao xe',
                'created_at' => now()->subYears(1),
                'updated_at' => now()->subDays(12)
            ]
        ];

        foreach ($profiles as $profile) {
            CustomerProfile::create($profile);
        }
    }
}
