<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FinanceOption;

class FinanceOptionSeeder extends Seeder
{
    public function run(): void
    {
        $options = [
            [
                'name' => 'Trả góp 12 tháng',
                'code' => 'FIN-12M',
                'bank_name' => 'Vietcombank',
                'description' => 'Khoản vay 12 tháng, lãi suất cố định.',
                'interest_rate' => 9.50,
                'processing_fee' => 500000,
                'min_tenure' => 6,
                'max_tenure' => 12,
                'min_down_payment' => 20.00,
                'min_loan_amount' => 50000000.00,
                'max_loan_amount' => 2000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Chứng minh thu nhập.',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Trả góp 36 tháng',
                'code' => 'FIN-36M',
                'bank_name' => 'Techcombank',
                'description' => 'Khoản vay 36 tháng, lãi suất ưu đãi.',
                'interest_rate' => 10.50,
                'processing_fee' => 700000,
                'min_tenure' => 12,
                'max_tenure' => 36,
                'min_down_payment' => 30.00,
                'min_loan_amount' => 100000000.00,
                'max_loan_amount' => 3000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Hợp đồng lao động, Sao kê lương.',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Gói vay 0% lãi suất',
                'code' => 'FIN-0-VCB',
                'bank_name' => 'Vietcombank',
                'description' => 'Ưu đãi đặc biệt 0% lãi suất trong 6 tháng đầu.',
                'interest_rate' => 0.00,
                'processing_fee' => 0,
                'min_tenure' => 6,
                'max_tenure' => 24,
                'min_down_payment' => 50.00,
                'min_loan_amount' => 200000000.00,
                'max_loan_amount' => 1500000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Bằng lái xe.',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Vay nhanh 24 tháng',
                'code' => 'FIN-24M-VPB',
                'bank_name' => 'VPBank',
                'description' => 'Duyệt nhanh trong 24h, thủ tục đơn giản.',
                'interest_rate' => 11.00,
                'processing_fee' => 1000000,
                'min_tenure' => 12,
                'max_tenure' => 24,
                'min_down_payment' => 25.00,
                'min_loan_amount' => 100000000.00,
                'max_loan_amount' => 2500000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe.',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Gói vay dài hạn 72 tháng',
                'code' => 'FIN-72M-ACB',
                'bank_name' => 'ACB',
                'description' => 'Vay lên đến 72 tháng, trả góp linh hoạt.',
                'interest_rate' => 12.50,
                'processing_fee' => 1500000,
                'min_tenure' => 36,
                'max_tenure' => 72,
                'min_down_payment' => 20.00,
                'min_loan_amount' => 200000000.00,
                'max_loan_amount' => 5000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Hợp đồng lao động, Sao kê 6 tháng.',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Trả góp ưu đãi 18 tháng',
                'code' => 'FIN-18M-MB',
                'bank_name' => 'MBBank',
                'description' => 'Gói ưu đãi cho khách hàng thân thiết.',
                'interest_rate' => 9.00,
                'processing_fee' => 0,
                'min_tenure' => 12,
                'max_tenure' => 18,
                'min_down_payment' => 30.00,
                'min_loan_amount' => 150000000.00,
                'max_loan_amount' => 2000000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe, Chứng minh thu nhập.',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Vay cấp tốc 6 tháng',
                'code' => 'FIN-6M-SHB',
                'bank_name' => 'SHB',
                'description' => 'Gói vay ngắn hạn, lãi suất thấp.',
                'interest_rate' => 8.50,
                'processing_fee' => 300000,
                'min_tenure' => 3,
                'max_tenure' => 6,
                'min_down_payment' => 40.00,
                'min_loan_amount' => 50000000.00,
                'max_loan_amount' => 500000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe.',
                'is_active' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Gói vay 48 tháng',
                'code' => 'FIN-48M-TPB',
                'bank_name' => 'TPBank',
                'description' => 'Lãi suất cạnh tranh, duyệt nhanh.',
                'interest_rate' => 10.00,
                'processing_fee' => 800000,
                'min_tenure' => 24,
                'max_tenure' => 48,
                'min_down_payment' => 25.00,
                'min_loan_amount' => 200000000.00,
                'max_loan_amount' => 3500000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Hợp đồng lao động.',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Vay VIP 60 tháng',
                'code' => 'FIN-60M-VCB',
                'bank_name' => 'Vietcombank',
                'description' => 'Dành cho khách hàng VIP, ưu đãi đặc biệt.',
                'interest_rate' => 9.80,
                'processing_fee' => 0,
                'min_tenure' => 36,
                'max_tenure' => 60,
                'min_down_payment' => 15.00,
                'min_loan_amount' => 500000000.00,
                'max_loan_amount' => 10000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Sao kê 12 tháng, Tài sản thế chấp.',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Trả góp linh hoạt 30 tháng',
                'code' => 'FIN-30M-HDBank',
                'bank_name' => 'HDBank',
                'description' => 'Linh hoạt thời gian trả, không phạt trả trước hạn.',
                'interest_rate' => 11.50,
                'processing_fee' => 600000,
                'min_tenure' => 18,
                'max_tenure' => 30,
                'min_down_payment' => 20.00,
                'min_loan_amount' => 100000000.00,
                'max_loan_amount' => 2000000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe, Chứng minh thu nhập.',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Gói vay sinh viên',
                'code' => 'FIN-SV-BIDV',
                'bank_name' => 'BIDV',
                'description' => 'Dành riêng cho sinh viên, lãi suất ưu đãi.',
                'interest_rate' => 7.50,
                'processing_fee' => 0,
                'min_tenure' => 12,
                'max_tenure' => 24,
                'min_down_payment' => 30.00,
                'min_loan_amount' => 50000000.00,
                'max_loan_amount' => 800000000.00,
                'requirements' => 'CMND/CCCD, Thẻ sinh viên, Giấy xác nhận người bảo lãnh.',
                'is_active' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'Vay nhanh online 12 tháng',
                'code' => 'FIN-12M-ONLINE',
                'bank_name' => 'Techcombank',
                'description' => 'Đăng ký online, duyệt tự động.',
                'interest_rate' => 10.80,
                'processing_fee' => 500000,
                'min_tenure' => 6,
                'max_tenure' => 12,
                'min_down_payment' => 35.00,
                'min_loan_amount' => 100000000.00,
                'max_loan_amount' => 1500000000.00,
                'requirements' => 'CMND/CCCD online, Xác thực khuôn mặt.',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Gói platinum 84 tháng',
                'code' => 'FIN-84M-VIB',
                'bank_name' => 'VIB',
                'description' => 'Gói cao cấp, thời gian vay dài nhất.',
                'interest_rate' => 13.00,
                'processing_fee' => 2000000,
                'min_tenure' => 48,
                'max_tenure' => 84,
                'min_down_payment' => 20.00,
                'min_loan_amount' => 500000000.00,
                'max_loan_amount' => 8000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Hợp đồng lao động, Sao kê 12 tháng, Tài sản thế chấp.',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Trả góp 0 đồng',
                'code' => 'FIN-0DOWN-SACOM',
                'bank_name' => 'Sacombank',
                'description' => 'Không cần trả trước, lãi suất ưu đãi tháng đầu.',
                'interest_rate' => 9.90,
                'processing_fee' => 1000000,
                'min_tenure' => 12,
                'max_tenure' => 36,
                'min_down_payment' => 0.00,
                'min_loan_amount' => 200000000.00,
                'max_loan_amount' => 2500000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Hợp đồng lao động, Sao kê 6 tháng.',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Vay ưu đãi nhân viên',
                'code' => 'FIN-EMP-OCB',
                'bank_name' => 'OCB',
                'description' => 'Dành cho nhân viên văn phòng, thủ tục đơn giản.',
                'interest_rate' => 8.80,
                'processing_fee' => 0,
                'min_tenure' => 12,
                'max_tenure' => 48,
                'min_down_payment' => 25.00,
                'min_loan_amount' => 150000000.00,
                'max_loan_amount' => 3000000000.00,
                'requirements' => 'CMND/CCCD, Hợp đồng lao động, Sao kê lương 3 tháng.',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Gói vay xanh',
                'code' => 'FIN-GREEN-AGRI',
                'bank_name' => 'Agribank',
                'description' => 'Ưu đãi cho xe điện và xe hybrid.',
                'interest_rate' => 7.00,
                'processing_fee' => 0,
                'min_tenure' => 12,
                'max_tenure' => 60,
                'min_down_payment' => 20.00,
                'min_loan_amount' => 300000000.00,
                'max_loan_amount' => 4000000000.00,
                'requirements' => 'CMND/CCCD, Giấy tờ xe, Cam kết mua xe xanh.',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Vay siêu tốc 9 tháng',
                'code' => 'FIN-9M-SEABANK',
                'bank_name' => 'SeABank',
                'description' => 'Giải ngân trong 2 giờ, thủ tục tối giản.',
                'interest_rate' => 12.00,
                'processing_fee' => 700000,
                'min_tenure' => 6,
                'max_tenure' => 9,
                'min_down_payment' => 40.00,
                'min_loan_amount' => 50000000.00,
                'max_loan_amount' => 1000000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe.',
                'is_active' => false,
                'sort_order' => 17,
            ],
            [
                'name' => 'Gói vay 42 tháng',
                'code' => 'FIN-42M-VIETBANK',
                'bank_name' => 'VietBank',
                'description' => 'Lãi suất cố định, không tăng theo thời gian.',
                'interest_rate' => 10.20,
                'processing_fee' => 900000,
                'min_tenure' => 24,
                'max_tenure' => 42,
                'min_down_payment' => 25.00,
                'min_loan_amount' => 200000000.00,
                'max_loan_amount' => 3000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Chứng minh thu nhập.',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Trả góp đặc biệt 15 tháng',
                'code' => 'FIN-15M-MSB',
                'bank_name' => 'MSB',
                'description' => 'Chương trình đặc biệt cuối năm.',
                'interest_rate' => 8.00,
                'processing_fee' => 400000,
                'min_tenure' => 12,
                'max_tenure' => 15,
                'min_down_payment' => 30.00,
                'min_loan_amount' => 100000000.00,
                'max_loan_amount' => 1800000000.00,
                'requirements' => 'CMND/CCCD, Bằng lái xe.',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Vay cao cấp 96 tháng',
                'code' => 'FIN-96M-SCBANK',
                'bank_name' => 'SCB',
                'description' => 'Dành cho xe hạng sang, hạn mức cao.',
                'interest_rate' => 14.00,
                'processing_fee' => 3000000,
                'min_tenure' => 60,
                'max_tenure' => 96,
                'min_down_payment' => 30.00,
                'min_loan_amount' => 1000000000.00,
                'max_loan_amount' => 15000000000.00,
                'requirements' => 'CMND/CCCD, Hộ khẩu, Sao kê 24 tháng, Tài sản thế chấp, Bảo hiểm.',
                'is_active' => true,
                'sort_order' => 20,
            ],
        ];

        foreach ($options as $o) {
            FinanceOption::updateOrCreate(['code' => $o['code']], $o);
        }
    }
}


