<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            // Admin users
            [
                'name' => 'Admin System',
                'email' => 'admin@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234567',
                'role' => 'admin',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(31),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=Admin',
                'employee_id' => 'ADM001',
                'department' => 'IT',
                'position' => 'System Administrator',
                'hire_date' => '2020-01-01',
                'created_at' => now()->subYears(4),
                'updated_at' => now()->subDays(10),
            ],
            [
                'name' => 'Manager Sales',
                'email' => 'manager@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234568',
                'role' => 'manager',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(400),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=Mgr',
                'employee_id' => 'MGR001',
                'department' => 'Sales',
                'position' => 'Sales Manager',
                'hire_date' => '2021-03-15',
                'created_at' => now()->subYears(3),
                'updated_at' => now()->subDays(8),
            ],
            
            // Sales staff
            [
                'name' => 'Nguyễn Văn A',
                'email' => 'sales1@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234569',
                'role' => 'sales_person',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(200),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=NV A',
                'employee_id' => 'SAL001',
                'department' => 'Sales',
                'position' => 'Sales Representative',
                'hire_date' => '2022-01-10',
                'created_at' => now()->subYears(2),
                'updated_at' => now()->subDays(5),
            ],
            [
                'name' => 'Trần Thị B',
                'email' => 'sales2@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234570',
                'role' => 'sales_person',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(180),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=TT B',
                'employee_id' => 'SAL002',
                'department' => 'Sales',
                'position' => 'Sales Representative',
                'hire_date' => '2022-02-20',
                'created_at' => now()->subYears(2),
                'updated_at' => now()->subDays(5),
            ],
            
            // Service staff
            [
                'name' => 'Lê Văn C',
                'email' => 'service1@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234571',
                'role' => 'technician',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(250),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=LV C',
                'employee_id' => 'SVC001',
                'department' => 'Service',
                'position' => 'Service Technician',
                'hire_date' => '2021-06-15',
                'created_at' => now()->subYears(3),
                'updated_at' => now()->subDays(6),
            ],
            [
                'name' => 'Phạm Thị D',
                'email' => 'service2@showroom.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234572',
                'role' => 'technician',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(230),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=PT D',
                'employee_id' => 'SVC002',
                'department' => 'Service',
                'position' => 'Service Advisor',
                'hire_date' => '2021-08-10',
                'created_at' => now()->subYears(3),
                'updated_at' => now()->subDays(6),
            ],
            
            // Customer users
            [
                'name' => 'Khách hàng VIP',
                'email' => 'vip@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234573',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(35),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=VIP',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(7),
            ],
            [
                'name' => 'Nguyễn Thị E',
                'email' => 'customer1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234574',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(20),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=NT E',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(10),
            ],
            [
                'name' => 'Trần Văn F',
                'email' => 'customer2@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234575',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(18),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=TV F',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(10),
            ],
            [
                'name' => 'Lê Thị G',
                'email' => 'customer3@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234576',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(15),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=LT G',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(12),
            ],
            [
                'name' => 'Phạm Văn H',
                'email' => 'customer4@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234577',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(12),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=PV H',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(12),
            ],
            [
                'name' => 'Hoàng Thị I',
                'email' => 'customer5@example.com',
                'password' => Hash::make('password123'),
                'phone' => '0901234578',
                'role' => 'user',
                'is_verified' => true,
                'verification_token' => null,
                'email_verification_sent_at' => now()->subDays(10),
                'two_factor_enabled' => false,
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'is_active' => true,
                'email_verified_at' => now(),
                'phone_verified_at' => now(),
                'last_login_at' => now(),
                'avatar_path' => 'https://placehold.co/128x128?text=HT I',
                'employee_id' => null,
                'department' => null,
                'position' => null,
                'hire_date' => null,
                'created_at' => now()->subMonths(2),
                'updated_at' => now()->subDays(12),
            ]
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}
